consolelabs/mochi-api

- pkg/handler/configs.go
-  `GET: api/v1/configs/twitter/hashtag/` returns 200 if empty
> chore: update hashtag config

- pkg/entities/nfts.go
- pkg/handler/nfts.go
- pkg/repo/nft_collection/mocks/store.go
- pkg/repo/nft_collection/pg.go
- pkg/repo/nft_collection/store.go
- pkg/routes/v1.go
- An API to update collection image to GCS hosted if needed, `PATCH: /api/v1/nfts/collections/<collection_address>`, no request body
> chore: update collection images

- cmd/update-user-role/main.go
- pkg/entities/configs.go
- pkg/entities/defi.go
- pkg/entities/guild.go
- pkg/entities/user.go
- pkg/job/update_user_roles.go
- pkg/response/guild.go
- pkg/service/coingecko/mocks/service.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
Currently we send moderation logs to configured channel via `$log`, but only applied for `tip` and `levelup`
Now we are sending logs for more activities
> feat: more moderation logs

- migrations/schemas/20220821150936-alter_guild_user_activity.sql
- pkg/entities/configs.go
- pkg/entities/defi.go
- pkg/entities/tokens.go
- pkg/handler/configs.go
- pkg/handler/defi.go
- pkg/repo/guild_user_activity_log/mocks/store.go
- pkg/repo/guild_user_activity_log/pg.go
- pkg/repo/guild_user_activity_log/store.go
- pkg/service/coingecko/mocks/service.go
-  `GET: /configs/tokens?guild_id=` returns global default tokens when `guild_id=""`
- Activity log `guild_id` is nullable to log DM activities
> chore: guild default tokens

- pkg/entities/default_role.go
- pkg/entities/user.go
- pkg/entities/webhook.go
- pkg/handler/default_roles.go
- pkg/handler/webhook_test.go
- pkg/response/default_role.go
-   [x] Fix default message
-   [x] Return empty role_id when default role not found
**Describe**
When new user join server, 2 event will be triggered:
- `messageCreate`
- `guildMemberAdd`
`messageCreate` run first and no user in database to process this event. So I consider it as a default action and does not create activity log in database.
- Default role:
- Errors:
> fix: default message

- pkg/entities/webhook.go
-   [x] Create user if not exist
**Description**
When bot is added to new server, it does have info of users in this server. So when user send message, bot cannot handle this and return error.
Error:
> chore: create user if not exist

- pkg/entities/user.go
- pkg/handler/webhook.go
- pkg/repo/guild_users/pg.go
- pkg/repo/guild_users/store.go
-   [x] Fix: invite tracker auto remove user address
-   [x] Move logic from handler to entities
**Bug**
When new user join server, event `guildMemberAdd` will be triggered and backend create user for both inviter and invitee. It make a bug and remove wallet address + wallet number if user exists in the database.
**Flow**
`HandleInviteTracker` flow:
> fix: invite tracker auto remove user wallet

- pkg/entities/webhook.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
GM streak send log message wrong:
- old: send to mochi_log_channel_id which is bot-logs in server Mochi
- new: send to log_channel per server (column log_channel in table discord_guilds)
> fix: send wrong gm streak log

- dbconfig.yml
- docker-compose.yml
- migrations/schemas/20220829174242-remove-activity_logs_users_fkey.sql
- pkg/config/config.go
- pkg/entities/auth.go
- pkg/entities/configs.go
- pkg/entities/defi.go
- pkg/entities/user.go
- pkg/entities/webhook.go
- pkg/handler/guilds.go
- pkg/job/fetch_discord_users.go
- pkg/model/user.go
- pkg/repo/users/pg.go
- pkg/repo/users/store.go
- pkg/util/testhelper/db.go
-> remove FK
Flow `GetOneOrUpsertUser()`:
1. User not exists -> create new
2. Already existed but no wallet -> generate wallet
3. Already existed but discord username updated -> update user
**PS: sorry for not providing any diagram**
> refactor: upsert users

- pkg/entities/defi.go
-   [x] return data = `nil` instead of error if watchlist is empty
> fix: no data found

- pkg/repo/user_nft_balance/pg.go
Config `Not a Pod Gang` requires 0 NFT
Config `Podians` requires 1 NFT
User has 1 NFT
- Old: assign role `Not a Pod Gang`
- New: assign role `Podians`
> fix: allow equal nft config

- pkg/entities/configs.go
- pkg/entities/discord.go
- pkg/entities/entity.go
- pkg/entities/user.go
- pkg/handler/default_roles.go
- pkg/job/update_user_roles.go
- pkg/util/discord.go
Clean up discord alerts - Do not send to Mochi's alert channel when error is one of these types
> chore: cleanup discord alerts

- pkg/entities/nfts.go
- pkg/model/solana.go
- Old: Get data on `off_chain_data` field, this is sometimes empty
- New: Get data in `data` field of Solana API, this always has data
> fix: solana contract name

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/configs.go
- pkg/response/config.go
- pkg/util/marketplace.go
- Add `explorer_link` and `chain_name` to api list nft-roles
```
"chain_name": "eth",
"explorer_url": "https://etherscan.io/address/0x7D1070fdbF0eF8752a9627a79b00221b53F231fA"
```
> chore: add explorer url to nft role

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- go.mod
- go.sum
- pkg/cache/cache.go
- pkg/cache/redis.go
- pkg/config/config.go
- pkg/entities/cache.go
- pkg/entities/discord.go
- pkg/entities/webhook.go
- pkg/handler/cache.go
- pkg/request/cache.go
- pkg/response/cache.go
- pkg/routes/v1.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
- pkg/util/discord.go
- Add API to cache vote message data
- Update `discordgo` package `v0.25 -> v0.26`
- Bot replies to the `$vote` message if it's in 5min
Reply to message in Mochi server
Reply to message outside Mochi server
> chore: cache upvote msg

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20220916154224-add_telegram_discord_id.sql
- pkg/entities/telegram.go
- pkg/handler/telegram.go
- pkg/model/user_telegram_discord_association.go
- pkg/repo/pg/repo.go
- pkg/repo/repo.go
- pkg/repo/user_telegram_discord_association/pg.go
- pkg/repo/user_telegram_discord_association/store.go
- pkg/request/telegram.go
- pkg/response/telegram.go
- pkg/routes/v1.go
> feat: telegram - discord associations

- pkg/job/update_gm_streak.go
- Fixed gm wrong timer
After running cronjob. Last record did not gm on 15/9 so on 16/9 it lose the streak
> chore: update gm job

- migrations/schemas/20220919171236-alter_user_telegram_discord_associations.sql
- pkg/entities/telegram.go
- pkg/handler/telegram.go
- pkg/model/user_telegram_discord_association.go
- pkg/repo/user_telegram_discord_association/pg.go
- pkg/repo/user_telegram_discord_association/store.go
- pkg/request/telegram.go
> refactor: link telegram by username

- pkg/repo/user_telegram_discord_association/pg.go
-   [x] Fixed upsert query (wrong `onConflict` clause): allow to re-link/update `telegram_username` by `discord_id`
**Media**
> fix: upsert linked telegram

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20220922124147-alter_users_add_nr_of_join.sql.sql
- pkg/entities/verification.go
- pkg/model/guild_config_wallet_verification_message.go
Update api create verify message: `POST /api/v1/verify/config`
Update logic api verify wallet: `POST /api/v1/verify`
https://www.loom.com/share/3488bfc1675946318ea4668da054d5c2
> feat: assign role verify wallet

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/defi.go
- pkg/handler/defi.go
- pkg/response/defi.go
- pkg/service/coingecko/coingecko.go
- pkg/service/coingecko/mocks/service.go
- pkg/service/coingecko/service.go
> refactor: pair for watchlist

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20220928145213-add_guild_active_status.sql
- pkg/entities/guild.go
- pkg/entities/guild_test.go
- pkg/handler/guilds.go
- pkg/handler/webhook.go
- pkg/handler/webhook_test.go
- pkg/model/discord_guild.go
- pkg/repo/discord_guilds/mocks/store.go
- pkg/repo/discord_guilds/pg.go
- pkg/repo/discord_guilds/store.go
- pkg/request/guild.go
- pkg/request/webhook.go
- pkg/response/guild.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
1. Handle `guildDelete` event sent to `/webhook`:
2. SELECT DB queries from `discord_guilds` will exclude guilds with `active` = `false`
> feat: handle bot removed event

- pkg/entities/guild.go
-   [x] When mochi joins new guild, `active` always = false
> fix: inactive when joins new guild

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/nfts.go
-   [x] Add NEKO and MAGICATS as default collection if user haven't added one
```
'http://localhost:8200/api/v1/nfts/watchlist?user_id=205167514731151360&page=0&size=12' \
```
> fix: nft watchlist default data

- pkg/entities/configs.go
- Before: `$welcome set channel` will reset welcome message to default
- Now: `$welcome set channel` will keep original message
> chore: fix welcome config

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/nfts.go
- pkg/entities/nfts_test.go
- pkg/handler/nfts.go
- pkg/handler/testdata/get_nft_detail/200-default.json
- pkg/handler/testdata/get_nft_detail/200-suggest.json
- pkg/repo/guild_config_default_collection/pg.go
- pkg/repo/guild_config_default_collection/store.go
- pkg/request/config.go
- pkg/request/nft.go
- pkg/response/nft.go
- pkg/response/response.go
- pkg/routes/v1.go
Refactor nft ticker flow:
Get guild default nft ticker: `GET /api/v1/configs/default-nft-ticker`
- Case 1: there's not any default in guild
Get collections from suggestiom: `GET /api/v1/nfts/collections/suggestion`
Create guild config default nft ticker: `POST /api/v1/configs/default-nft-ticker`
Get ticker: `GET /api/v1/nfts/:symbol/ticker -> /api/v1/nfts/ticker?symbol=neko&collection_address=0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE73&chain_id=250
`
- Case 2: there's default ticker in guild
Get ticker: `GET /api/v1/nfts/:symbol/ticker -> /api/v1/nfts/ticker?symbol=neko&collection_address=0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE73&chain_id=250
`
> refactor: flow nft ticker

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20221013134724-conversation_repost_histories.sql
- pkg/consts/configs.go
- pkg/entities/configs.go
- pkg/entities/configs_test.go
- pkg/handler/configs.go
- pkg/handler/testdata/guild_config_repost_reactions/200-exist-guild-config-repost-reaction.json
- pkg/handler/webhook.go
- pkg/model/conversation_repost_histories.go
- pkg/model/guild_config_repostable_reaction.go
- pkg/repo/conversation_repost_histories/pg.go
- pkg/repo/conversation_repost_histories/store.go
- pkg/repo/guild_config_repost_reaction/mocks/store.go
- pkg/repo/guild_config_repost_reaction/pg.go
- pkg/repo/guild_config_repost_reaction/store.go
- pkg/repo/pg/repo.go
- pkg/repo/repo.go
- pkg/request/config.go
- pkg/response/message_repost_history.go
- pkg/routes/v1.go
> feat: sb start stop conversation

- pkg/entities/quest.go
- pkg/repo/quest/pg.go
- pkg/repo/quest/query.go
- pkg/repo/quest/store.go
- pkg/request/quest.go
- pkg/routes/v1.go
e.g. user said `gm` before run `$quest` => `$quest` returns `GM` quest progress = `0/1`
> fix: quest issues

- cmd/cleanup-expired-assign-contract/main.go
- migrations/schemas/20220928170237-create-offchain_tip_bot-tables.sql
- pkg/entities/offchain_tip_bot_contract.go
- pkg/job/clean_up_expired_assign_contract.go
- pkg/model/offchain_tip_bot_assign_contract.go
- pkg/model/offchain_tip_bot_assign_contract_log.go
- pkg/repo/offchain_tip_bot_chain/pg.go
- pkg/repo/offchain_tip_bot_contract/pg.go
- pkg/repo/offchain_tip_bot_contract/store.go
-   [x] add job to clean up assign contract
-   call `/api/v1/offchain-tip-bot/assign-contract` to create an assign contract, check table `offchain_tip_bot_assign_contract`, `offchain_tip_bot_assign_contract_logs`
- run `go run ./cmd/cleanup-expired-assign-contract/main.go` to test job clean up expired assign contract
> feat: job clean up expired assign contract

- migrations/schemas/20221019150033-alter_guild_config_repost_reactions.sql
- pkg/repo/guild_config_repost_reaction/pg.go
-   [x] Fix when set the same emoji in 2 servers discord for reaction message repost, the latest server set will overwrite config with the emoji, so previous server set config with the emoji will disappear.
$sb set-chat
https://www.loom.com/share/8c762aa2be13434bb3161004141d17d3
> chore: append list conversation repost config

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20221026135921-remove-to-address-fields-of-trade-offers-table.sql
- pkg/entities/trade.go
- pkg/model/trade_offer.go
- pkg/repo/trade_offer/pg.go
- pkg/request/trade.go
- Create
```shell
curl -X 'POST' \
'http://localhost:8200/api/v1/trades' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"have_items": [
{
"token_address": "0x5417A03667AbB6A059b3F174c1F67b1E83753046",
"token_ids": [
"1", "2", "3"
]
}
],
"owner_address": "0x5417A03667AbB6A059b3F174c1F67b1E83753046",
"want_items": [
{
"token_address": "0xAEeE56fe367381f29510C27F1Dae815E9591d60a",
"token_ids": [
"2", "4"
]
}
]
}'
```
- GET
```shell
'http://localhost:8200/api/v1/trades/{created_trade_id}' \
```
> fix: update field trade offers

- pkg/entities/quest.go
- pkg/repo/quest_streak/pg.go
- pkg/repo/quest_streak/query.go
> fix: quest - vote streak multiplier

- pkg/entities/quest.go
- pkg/repo/quest_streak/pg.go
- pkg/request/quest.go
-   [x] Update claim quest rewards API `[POST] /api/v1/quests/claim`: allow to claim rewards by quest_id
```
curl --location --request POST 'http://localhost:8200/api/v1/quests/claim' \
--header 'Content-Type: application/json' \
--data-raw '{
"user_id": "760874365037314100",
"routine": "daily",
"quest_id": "7d767919-38e1-4d81-aad9-3815f8fa8547"
}'
```
> feat: support claim by quest

- pkg/service/discord/discord.go
-   [x] Add prefix to feedback button so Mochi Bot can detect
> fix: add prefix to feedback button

- pkg/entities/defi.go
Background: Wrong `interval` and `limit` params in nghenhan API request -> wrong chart data range -> incorrect number of data points
-> Solutions
e.g.
- range = 7d -> 7 * 24 = 168 data points
- range = 90d -> 90 data points
> fix: fiat historical data range

- pkg/entities/twitter.go
-   [x] Fix twitter streak logic: if yser already posted at least 1 tweet today, only +1 to `total_count`
> fix: twitter streak logic

- migrations/schemas/20221207153722-add_nft_add_request_history.sql
- pkg/entities/data_webhook.go
- pkg/entities/nfts.go
- pkg/entities/nfts_test.go
- pkg/handler/data_webhook.go
- pkg/handler/nfts_test.go
- pkg/model/nft_add_request_history.go
- pkg/repo/nft_add_request_history/pg.go
- pkg/repo/nft_add_request_history/query.go
- pkg/repo/nft_add_request_history/store.go
- pkg/repo/pg/repo.go
- pkg/repo/repo.go
- pkg/request/data_webhook.go
- pkg/routes/v1.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
- pkg/service/indexer/indexer.go
**Media**
- Mochi logs
- Reply to original command
> feat: notify complete nft sync

- pkg/repo/offchain_tip_bot_contract/pg.go
Reason: Wrong usage of `FirstOrCreate()`: no condition in the query == `SELECT * FROM "offchain_tip_bot_assign_contract" LIMIT 1`
=> returns wrong contract address
> fix: assign contract

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/dao_proposal.go
- pkg/entities/dao_vote.go
- pkg/handler/dao-voting/dao-voting.go
- pkg/handler/data/data.go
- pkg/handler/data/interface.go
- pkg/handler/defi/defi.go
- pkg/repo/dao_proposal/pg.go
- pkg/repo/dao_proposal/store.go
- pkg/repo/guild_config_dao_tracker/pg.go
- pkg/repo/guild_config_dao_tracker/store.go
- pkg/response/dao_proposal.go
- pkg/response/defi.go
- pkg/routes/v1.go
- new api to get usage stats for dao tracker and guild dao proposal
- add new query `guild_id` to existing `/api/v1/dao-voting/proposals`
> feat: proposal internal

- migrations/schemas/20230221225001-remove_offchain_tip_bot_user_constraints.sql
- pkg/entities/offchain_tip_bot.go
- pkg/model/offchain_tip_bot_transfer_history.go
-   [x] Sometimes bot fails to fetch user data so tipping may lead to errors
-> Remove user constrains from offchain table
> fix: remove user constraints from offchain tables

- cmd/watch-coin-price-change/main.go
- cmd/watch-dm-notify-price-alert/main.go
- migrations/schemas/20230222164928-alter_user_token_price_alert.sql
- pkg/cache/cache.go
- pkg/cache/redis.go
- pkg/entities/cache.go
- pkg/entities/defi.go
- pkg/job/watch_coin_price_change.go
- pkg/job/watch_dm_notify_price_alert.go
- pkg/model/errors/validator.go
- pkg/model/user_token_price_alert.go
- pkg/repo/user_token_price_alert/pg.go
- pkg/repo/user_token_price_alert/store.go
- pkg/request/defi.go
- pkg/response/binance.go
- pkg/response/cache.go
- pkg/response/defi.go
- pkg/service/binance/binance.go
- pkg/service/binance/service.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
-  [x] Add `watchCoinPriceChanges` worker
-  [x] Add `watchDMNotifyPriceAlert` worker
1. Run `make migrate-up`
2. Open two seperate terminal sessions and run below cmds:
- `go run cmd/watch-dm-notify-price-alert/main.go`
- `go run cmd/watch-coin-price-change/main.go`
3. Add new record by API to see how this two workers operate
- Create new alert 
[POST] http://localhost:8200/api/v1/defi/price-alert
Sample req: `{
"user_discord_id": "490895538892439553",
"symbol": "btc",
"alert_type": "price_drops_to",
"frequency": "only_once",
"value": 24050
}`
- Remove an Alert
[DELETE] http://localhost:8200/api/v1/defi/price-alert
Sample req: 
**Notes:**
- Supported symbols are in this list (BTC, ETH, BNB, SOL, FTM, MAGIC). **Logic for this should be finanally …
> chore: add workers for price alert system 

- pkg/job/watch_evm_deposits.go
currently we're querying 1000 txns / contract while running job watch-evm-deposits (interval = 5m)
-> 1 txn = 0.1 credit
-> we only have 100k monthly credits, so we will reduce query size from 1000 to 100 to avoid covalent API rate limit
> fix: evm despoit job - reduce tx query size

- pkg/chain/chain.go
-   [x] Call directly to contract to get token balance instead of using etherscan (since lack of stability)
> fix: raw erc20 token balance

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/guild.go
- pkg/entities/guild_test.go
- pkg/handler/user/user.go
- pkg/response/guild.go
- pkg/service/discord/discord.go
- pkg/service/discord/mocks/service.go
- pkg/service/discord/service.go
-   [x] Fix API `GET /guilds/:guild_id` to return guild's icon url also
-   [x] Update docs
> Fix: get guild detail - return guild's icon

- pkg/repo/users/pg.go
-   [x] Whitelist `discriminator` for updating on conflicting when executing upsert many users
> fix: upsert users - update discriminator on conflict

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/entities/defi.go
- pkg/handler/config-defi/config.go
- pkg/handler/config-defi/interface.go
- pkg/repo/guild_config_default_ticker/pg.go
- pkg/repo/guild_config_default_ticker/store.go
- pkg/response/nft.go
- pkg/routes/v1.go
-   [x] API get list default ticker of a guild
```sh
'http://localhost:8200/api/v1/config-defi/default-ticker/1003627546014916688' \
```
> feat: get list default ticker of a guild

- pkg/entities/configs.go
- pkg/entities/configs_test.go
- pkg/entities/user.go
- pkg/handler/user/testdata/users/200-top-users.json
- pkg/model/guild_user_xp.go
- pkg/repo/guild_config_level_role/mocks/store.go
- pkg/repo/guild_config_level_role/pg.go
- pkg/repo/guild_config_level_role/store.go
-   [x] Update `/api/v1/users/topAdd`: additional info - `currentLevelRole` and `nextLevelRole`
> fix: top users response

- migrations/schemas/20230828140930-alter_product_changelogs.sql
- migrations/schemas/20230828141030-add_product_changelog_views.sql
- pkg/entities/product_data.go
- pkg/handler/api-key/interface.go
- pkg/handler/product-data/interface.go
- pkg/handler/product-data/product_data.go
- pkg/model/product_bot_commands.go
- pkg/repo/pg/repo.go
- pkg/repo/product_changelogs_view/pg.go
- pkg/repo/product_changelogs_view/query.go
- pkg/repo/product_changelogs_view/store.go
- pkg/repo/repo.go
- pkg/request/product_data.go
- pkg/response/product_metadata.go
- pkg/routes/v1.go
-   [x] Add product changelogs view
-   [x] Add `file_name` field for `product_changelogs` table
-   [x] No UI commands affect by this change
-  [x] Create product changelogs view record
```sh
curl --request POST 'http://localhost:8200/api/v1/product-metadata/changelogs/view' \
--header 'Content-Type: application/json' \
--data '{
"profile_id": "1677175883678355456",
"changelog_name": "2023-19-08.md"
}'
```
-  [x] get product changelogs view
```sh
curl --request GET 'http://localhost:8200/api/v1/product-metadata/changelogs/view?changelog_name=2023-19-08.md' \
--header 'Content-Type: application/json'
```
> feat: add product changelogs view

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20230913115451-add-friend-tech-key-watchlist-items.sql
- pkg/entities/friend_tech_key.go
- pkg/handler/community/testdata/feedback/200-get-all-user-feedback.json
- pkg/handler/config-roles/config_test.go
- pkg/handler/defi/defi.go
- pkg/handler/defi/interface.go
- pkg/handler/defi/testdata/get_coin/200-success-eth.json
- pkg/handler/product-data/product_data.go
- pkg/model/errors/validator.go
- pkg/model/friend_tech_key.go
- pkg/repo/friend_tech_key_watchlist_item/pg.go
- pkg/repo/friend_tech_key_watchlist_item/store.go
- pkg/repo/pg/repo.go
- pkg/repo/repo.go
- pkg/request/friend_tech.go
- pkg/response/friend_tech.go
- pkg/routes/v1.go
Add apis to service track a friend tech key
- Api track
```
curl -X 'POST' \
'http://localhost:8200/api/v1/defi/tracking-keys' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"decrease_alert_at": 0,
"increase_alert_at": 0,
"key_address": "0xfd7232e66a69e1ae01e1e0ea8fab4776e2d325a9",
"profile_id": "1111"
}'
```
- Api untrack
```
curl -X 'DELETE' \
'http://localhost:8200/api/v1/defi/tracking-keys/6' \
```
- Api update track config
```
curl -X 'PUT' \
'http://localhost:8200/api/v1/defi/tracking-keys/9' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"decrease_alert_at": 100,
"increase_alert_at": 1
}'
```
- Api get list tracking keys by profile id
``` …
```
> feat: friend tech key tracking apis

- pkg/kafka/producer.go
nếu push trực tiếp vào thì sẽ bị mất message (thường là message cuối) vì nếu Flush mà message chưa kịp vào channel -> ko có gì để flush
> fix: produce kafka message using buildin utility

- .github/workflows/ci-test.yml
- Dockerfile
- update Dockerfile, reduced build time upto 20s
> chore: update dockerfile

- pkg/entities/friend_tech_key.go
- pkg/handler/defi/defi.go
- pkg/response/friend_tech.go
Update 3 APIs `GET/POST/PUT /tracking-keys` for returning the 24h price change percentage
> feat: add tracking key price change percentage

- pkg/job/cache_profile_commands.go
- pkg/model/profile_command_usage.go
- pkg/repo/profile_command_usage/pg.go
- cache profile cmd: need to group by `platform` as well
- /profile
> fix: cache profile cmd - grouped by platform

- pkg/entities/defi.go
- pkg/model/errors/validator.go
- pkg/service/geckoterminal/geckoterminal.go
- pkg/service/geckoterminal/model.go
> fix(get-market-chart): handle app panic when geckoterminal return err or empty

- pkg/service/friendtech/friend_tech.go
Got error 
```
{"hostname":"track-friend-tech-keys-28284200-pcg6r","level":"info","msg":"discord intents: 64","service":"mochi-api","time":"2023-10-11T19:23:30Z"}
{"hostname":"track-friend-tech-keys-28284200-pcg6r","level":"info","msg":"Connected to discord: Mochi Bot","service":"mochi-api","time":"2023-10-11T19:23:31Z"}
{"hostname":"track-friend-tech-keys-28284200-pcg6r","level":"info","msg":"start tracking friend tech keys","service":"mochi-api","time":"2023-10-11T19:23:33Z"}
{"error":"Get \"https://api.friendscan.tech/transactions?subjectAddress=0xfd7232e66a69e1ae01e1e0ea8fab4776e2d325a9\u0026limit=50\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","keyAddress":"0xfd7232e66a69e1ae01e1e0ea8fab4776e2d325a9","level":"error","limit":50,"msg":"[entity.GetFriend …
```
> fix: friend tech key api - add client id

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20231031114959-add_available_cmds_to_guilds.sql
- pkg/entities/guild.go
- pkg/model/discord_guild.go
- pkg/request/guild.go
- pkg/response/guild.go
- store cmds that a guild is using
> feat(cmd): add available cmds to discord guild

- pkg/entities/user.go
- pkg/entities/vault.go
- pkg/entities/wallet.go
- pkg/service/mochiprofile/mochiprofile.go
- pkg/service/mochiprofile/service.go
> fix: add auth query profile

- pkg/entities/vault.go
> fix: handle case create vault req

- pkg/service/binance/binance.go
- pkg/service/birdeye/birdeye.go
- pkg/service/chainexplorer/chainexplorer.go
- pkg/service/coingecko/adapter.go
- pkg/service/coingecko/coingecko.go
- pkg/service/covalent/adapter.go
- pkg/service/covalent/covalent.go
- pkg/service/dexscreener/dexscreener.go
- pkg/service/ethplorer/ethplorer.go
- pkg/service/friendtech/friend_tech.go
- pkg/service/krystal/krystal.go
- pkg/service/nghenhan/nghenhan.go
- pkg/service/service.go
- pkg/service/skymavis/adapter.go
- pkg/service/skymavis/skymavis.go
- pkg/service/solscan/adapter.go
- pkg/service/solscan/solscan.go
- pkg/service/sui/adapter.go
- pkg/service/sui/sui.go
> fix: add sentry service layer

- pkg/entities/offchain_tip_bot.go
> fix: add theme transaction v2

- pkg/service/friendtech/friend_tech.go
- Issue1: Someone added sentry for this service without initiating.
- Issue2: FriendTech change api endpoint: `FRIEND_SCAN_API='https://api.friendscan.io'`
> fix: friendtech svc is missing initiating sentry

- pkg/service/coingecko/adapter.go
> fix: update get coingecko market cache time to 5 minutes

- pkg/service/geckoterminal/geckoterminal.go
Got this error when trying to call gecko terminal API
```
app.geckoterminal.com\nChecking if the site connection is secure\napp.geckoterminal.com needs to review the security of your connection before proceeding.\nRay ID: 84085bd5addd48f4\nPerformance \u0026 security by Cloudflare
```
Look relate to bot restriction mechanism of web. So maybe we need using proxy to avoid it.
> chore: add proxy options when connect browserless host

- pkg/entities/defi.go
- pkg/entities/tokens.go
- pkg/handler/defi/defi.go
SearchCoins: revert logic
- Reason: we should not force search coins API to query by symbol. This may reproduce a legacy bug so just keep tracking
> fix: revert logic of SearchCoins

- pkg/service/binance/adapter/adapter.go
- pkg/service/binance/adapter/do.go
- pkg/service/binance/adapter/response.go
- pkg/service/binance/binance.go
- Binance future account: DO NOT send error to sentry if the error is related to API key permission
> fix: binanace future - ignore permission error

- pkg/service/covalent/adapter.go
- I tried to spam the get solana balance from covalent api but could not reproduce the bug, so I kept the sentry log and replaced `err `-> `res.Error`, if the sentry log occurs again, I can know the cause of the error and handle it later.
> fix(covalent): remove sentry log for covalent rate limit

- pkg/entities/defi.go
- pkg/response/defi.go
- pkg/util/solana.go
Get coin: self calculate market cap if data is not supported by coingecko
> fix: self calculate market cap if not supported

- pkg/chain/chain.go
- pkg/entities/defi.go
- pkg/repo/chain/pg.go
- pkg/repo/chain/query.go
- pkg/repo/chain/store.go
- Get coin API: support market cap data (if coingecko does not support) for evm-based tokens
> fix: get coin - support market cap data for evm tokens

- pkg/chain/chain.go
- pkg/entities/defi.go
- pkg/response/defi.go
- pkg/util/solana.go
- Get coin: new flag `ownership_renounced` to show if the token contract is renounced
> feat: ticker - add contract renounced

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- migrations/schemas/20240510080916-add-price_in_usd-col-to-binance-txs-table.sql
- pkg/entities/wallet.go
- pkg/handler/dex/dex.go
- pkg/handler/dex/interface.go
- pkg/model/binance_asset_average_cost.go
- pkg/model/binance_spot_transaction.go
- pkg/repo/binance_spot_transaction/pg.go
- pkg/repo/binance_spot_transaction/store.go
- pkg/routes/v1.go
- pkg/scheduler/update-binance-spot-history.go
- pkg/service/binance/adapter/adapter.go
- pkg/service/binance/binance.go
- pkg/service/binance/service.go
- Need to run migrate-up
```sh
curl --request GET \
--url 'http://localhost:8200/api/v1/users/43418/cexs/binance/average-costs?base=FTM&guild_id=891310117658705931&interval=30&target=USD'
```
> feat: binance spot average cost

- pkg/response/binance.go
- pkg/scheduler/update-binance-spot-history.go
- pkg/service/binance/adapter/adapter.go
- pkg/service/binance/binance.go
- pkg/service/binance/service.go
> fix: add wd and dep tx binance

- migrations/schemas/20240524142655-add-soft-delete-vaults-table.sql
- pkg/model/vault.go
- pkg/repo/vault/pg.go
- pkg/repo/vault/query.go
> feat: vault soft delete

- pkg/job/cache_profile_commands.go
> fix: remove krystal earn balance
