pkg/entities/webhook.go
pkg/handler/webhook.go
pkg/request/webhook.go

-   handle boost event from bot

feat: xp for boosters

---

pkg/entities/webhook.go

feat: create GmXPIncrease

---

pkg/entities/reaction_roles.go

-  add function to check if emoji was already configured

chore: add some validation stuffs

---

pkg/consts/stat_count_type.go
pkg/entities/discord.go
pkg/entities/entity.go
pkg/handler/guilds.go
pkg/util/stat.go
pkg/util/util.go

-   [x] Add highest ticker feature
-   Use API /v1/guilds/<guild_id>/channels?count_type=highest_ticker&symbol= <coin_id>&interval=<number_of_days>
-   coin_id must be correct from coin gecko API

feat: highest ticker

---

pkg/entities/tokens.go
pkg/entities/tokens_test.go
pkg/handler/custom_token.go
pkg/request/token.go

chore: update chain and chain id

---

pkg/entities/nfts.go

-   [x] Change api and response to indexer

chore: change api to indexer

---

pkg/entities/user_test.go

chore: update writing test for get-top-user

---

pkg/entities/chain.go
pkg/entities/chain_test.go
pkg/handler/chain.go
pkg/routes/v1.go

**Add api for list all chains**
Get /api/v1/chains
**Response sample:** 
```
{
"data": [
{
"id": 1,
"name": "Ethereum Mainnet",
"currency": "ETH"
},
{
"id": 56,
"name": "Binance Smart Chain Mainnet",
"currency": "BNB"
},
{
"id": 250,
"name": "Fantom Opera",
"currency": "FTM"
}
]
}
```

feat: create api get all chains

---

pkg/handler/custom_token.go

fix: fix error response custom token

---

pkg/entities/entity.go
pkg/handler/nfts.go
pkg/response/nft_collection.go
pkg/routes/v1.go
pkg/service/indexer/indexer.go
pkg/service/indexer/service.go

-   [x] Add NFT top trading volume API
-  GET: ```localhost:8200/api/v1/nfts/trading-volume?limit=<nr_of_nft>```
```
{
"data": [
{
"collection_address": "0x7acee5d0acc520fab33b3ea25d4feef1ffebde71",
"collection_name": "Cyber Neko 2",
"collection_symbol": "neko_2",
"collection_chain_id": 250,
"trading_volume": 981245.54,
"token": "ftm"
},
{
"collection_address": "0x7D1070fdbF0eF8752a9627a79b00221b53F231fA",
"collection_name": "Cyber Rabby",
"collection_symbol": "rabby",
"collection_chain_id": 1,
"trading_volume": 123456.19,
"token": "eth"
},
{
"collection_address": "0x7acee5d0acc520fab33b3ea25d4feef1ffebde68",
"collection_name": "Cyber Neko 12",
"collection_symbol": "neko_12",
"collection_chain_id": 250,
"trading_volume": 94682.35,
"token": "ftm" …
```

feat: top nft volume

---

migrations/schemas/20220616110601-guild_config_sales_tracker.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_config_sales_tracker.go
pkg/repo/guild_config_sales_tracker/pg.go
pkg/repo/guild_config_sales_tracker/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/routes/v1.go

- Add config API for sales tracker
- ```GET: /api/v1/configs/sales-tracker?guild_id=<guild_id>```
****GET response****
```
{
"data": {
"id": <uuid>,
"guild_id": <string>,
"channel_id": <string>
},
"message": "OK"
}
```
- ```POST: /api/v1/configs/sales-tracker```
****POST body:****
```
{
"guild_id": <string>,
"channel_id": <string>
}
```
****POST response:****
```
{
"message": "OK"
}
```

feat: sales tracker config

---

pkg/consts/discord.go
pkg/entities/webhook.go
pkg/handler/webhook.go
pkg/request/webhook.go

-   change XP for booster flow to be handled in MessageCreate event

chore: update XP for booster flow

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/model/nft_sales_tracker.go
pkg/repo/nft_sales_tracker/mocks/store.go
pkg/repo/nft_sales_tracker/pg.go
pkg/repo/nft_sales_tracker/store.go
pkg/response/nft_sales_tracker.go
pkg/routes/v1.go

-   [ ] Get all sales tracker API
-   ```GET: /api/v1/nfts/sales-tracker ```
-   Work in progress

feat: get sales tracker api

---

pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi.go

Fix logic for compare token
Sample
```
Get /api/v1/defi/coins/compare?source_symbol=btc&interval=7&target_symbol=bnb
```

chore: fix logic compare token

---

pkg/entities/nfts.go
pkg/response/nft.go
pkg/service/indexer/indexer.go
pkg/service/indexer/mocks/service.go
pkg/service/indexer/service.go

- Update indexer GetNFTDetail function
- Add indexer GetNFTContract function

chore: update indexer detail

---

migrations/schemas/20220512114402-alter-table-nft-collection-add-verified-column.sql
pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/model/nft_collection.go

update logic nft collection
Add check is_sync if
```
true -> done with sync
false -> in sync progress 
```

chore: update logic nft collection

---

migrations/schemas/20220629095836-alter-nft-collection-add-created-at.sql
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/model/nft_collection.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/response/nft_collection.go
pkg/routes/v1.go

-   [x] Add api nft new listed
-   [x] Unit test
-  ` GET: /api/v1/nfts/new-listed?interval=<days>&size=<number>&page=<number>`
- interval: in the last n days, default to 7 if left blank
- size: number of records in a page, default to 10 if left blank
- page: current position, default to 1 if left blank
Reponse:
```
{
"page": 1,
"size": 3,
"total": 11,
"data": [
{
"id": "05b1a563-1499-437f-b1e8-da4e630ab3ad",
"address": "0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE79",
"name": "neko",
"symbol": "neko",
"chain_id": "250",
"erc_format": "721",
"is_verified": true,
"created_at": "2022-06-29T03:28:53.122813Z"
},
{
"id": "42970b6d-e141-4162-8529-7f961baf9fce",
"address": "0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE78",
"name": "neko",
"symbol": "neko", …
```

feat: newly listed nft

---

pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/repo/nft_collection/pg.go

-  Update GetNewListedNFT pagination, first page index is now 0

chore: update new listed

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/model/nft_collection.go

-  Add new field: `Chain: string` to NFTCollection response

chore: update nft model

---

pkg/entities/nfts_test.go
pkg/model/nft_collection.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/response/nft_collection.go

-  Move response struct to another model, return NFTCollection struct to original

chore: update new listed nft

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/configs.go
pkg/handler/nfts.go
pkg/request/nft_sales_tracker.go
pkg/routes/v1.go

- Update sales-tracker API
- Remove add sales-tracker config API
- `POST: /api/v1/nfts/sales-tracker`
Post body:
```
{
"guild_id": <guild ID>,
"channel_id": <channel ID>,
"platform": <chain ID>,
"contract_address": <address>
}
```
Valid response:
```
{
"message": "OK"
}
```

chore: update sales tracker

---

pkg/entities/nfts_test.go
pkg/response/nft.go

- Add unit test for GetNFTDetail

chore: update nft tests

---

pkg/entities/nfts.go
pkg/handler/nfts.go

chore: updating logic nft add

---

migrations/schemas/20220707094341-alter-nft-collection-add-image.sql
pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/response/nft_collection.go

- GetNFTCollections now query DB instead of indexer
- Add new field `image` to `nft_collections` table

chore: update get collection api

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go

feat: create get NftDetailByName

---

pkg/config/config.go
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/response/marketplace.go
pkg/service/marketplace/marketplace.go
pkg/service/marketplace/mocks/service.go
pkg/service/marketplace/service.go

- `nft add` now call to marketplace to get image url

chore: update nft add

---

pkg/entities/discord_webhook.go
pkg/request/sales.go
pkg/util/urlMarketPlace.go

Update UI for discord webhook
add Token ID for hyperLink opensea

chore: updating discord webhook UI

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go

- write error log for tracking flow of nft entites

chore: update log for nft entities

---

pkg/entities/discord_webhook.go
pkg/handler/sales.go

- Webhook request now query data from indexer and database
- Add new API to get single collection from database

chore: update webhook data

---

pkg/entities/entity.go
pkg/handler/handler.go
pkg/handler/nfts.go

- Add a logger to struct Handler 
- `h.log.<function>`

chore: add handler log

---

pkg/entities/discord_webhook.go
pkg/handler/sales.go
pkg/request/sales.go
pkg/util/util.go

-  Changed some data type for webhook request

chore: update webhook

---

pkg/entities/configs.go
pkg/entities/message_repost_history.go
pkg/handler/webhook.go

-   Fix API return without response that causes `JSON parsing error`

chore: fix return without response => bot json parsing error

---

pkg/entities/discord_webhook.go
pkg/util/address.go

- Add timestamp to sales message
- Change shortened address format

chore: update webhook sales msg

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go

- Add more unit tests for entities package
- NFT query now uses image from db instead of indexer

chore: update nft test

---

pkg/entities/discord.go
pkg/entities/guild.go
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/response/nft_collection.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/discord_test.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- Update notify new guild message
- Add API `GET: /nfts/collection/stats` to get the count of each chain
- Refactor log functions
**Media**
Response

chore: update stats

---

cmd/post-twitter-nft-sales/main.go
go.mod
go.sum
migrations/schemas/20220802115658-guild_config_twitter_feed.sql
migrations/schemas/20220803011626-mochi_nft_sales.sql
pkg/entities/configs.go
pkg/entities/discord_webhook.go
pkg/entities/twitter.go
pkg/entities/webhook.go
pkg/handler/configs.go
pkg/handler/webhook.go
pkg/job/post_twitter_nft_sales.go
pkg/model/guild_config_twitter_feed.go
pkg/model/twitter.go
pkg/repo/guild_config_twitter_feed/pg.go
pkg/repo/guild_config_twitter_feed/store.go
pkg/repo/mochi_nft_sales/pg.go
pkg/repo/mochi_nft_sales/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/twitter.go
pkg/request/webhook.go
pkg/routes/v1.go
pkg/service/service.go
pkg/service/twitter/service.go
pkg/service/twitter/twitter.go
pkg/util/twitter.go

- Webhook for message from `#sales-feed` channel
Flow: new sale message -> webhook with message's data -> database with `is_notified_twitter = false` -> cronjob query all records and post to Twitter for all credentials -> set `is_notified_twitter = true` -> delete all records
- API to get/post twitter bot credentials `is_notified_twitter = false`
- Cronjob to post tweets (to edit UI look into pkg/service/twitter/twitter.go at comment `// edit post UI`
**Media**
API to config Twitter sale
Record created by webhook

feat: twitter sales feed

---

migrations/schemas/20220803173716-guild_config_twitter_hashtags.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_config_twitter_hashtag.go
pkg/repo/guild_config_twitter_hashtag/pg.go
pkg/repo/guild_config_twitter_hashtag/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/routes/v1.go

- API to get/create hashtag config
- `GET: /api/v1/configs/twitter/hashtag/<guild_id>`
- `POST: /api/v1/configs/twitter/hashtag`
- `DELETE  /api/v1/configs/twitter/hashtag/<guild_id>`
POST body
GET response

feat: config twitter hashtag

---

pkg/service/twitter/twitter.go

chore: update cronjob

---

migrations/schemas/20220804115252-alter_guild_config_twitter_hashtags.sql
pkg/entities/configs.go
pkg/model/guild_config_twitter_hashtag.go
pkg/repo/guild_config_twitter_hashtag/pg.go
pkg/repo/guild_config_twitter_hashtag/store.go
pkg/request/config.go
pkg/response/config.go

- Add `user_id` and `created_at` to twitter hashtag config API

chore: update hashtag config

---

pkg/handler/configs.go

chore: update hashtag

---

pkg/handler/configs.go

- Remove log error `record not found`

chore: update hashtag api

---

pkg/config/config.go
pkg/entities/discord_webhook.go
pkg/response/marketplace.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/service/marketplace/marketplace.go

****Temporarily disable, waiting for listing webhook****

feat: steal alert

---

migrations/schemas/20220808131033-alter_mochi_nft_sales.sql
pkg/entities/discord_webhook.go
pkg/handler/webhook.go
pkg/model/twitter.go
pkg/request/twitter.go
pkg/service/twitter/twitter.go
pkg/util/util.go

-   [x] Remove logic to upload image to twitter
-   [x] Modify the tweet content
-  call this curl
```
curl --location --request POST 'http://localhost:8200/api/v1/webhook/nft' \ 
--header 'x-api-key: aa2c97f7294d4d79b9b17df82739e524' \
--header 'Content-Type: application/json' \
--data-raw '{
"event": "sales",
"collection_address": "0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE73",
"token_id": "1",
"transaction": "0xf2db72ba2348e2f718a6118c12fead737333a7a5de5c0fa35682c9fc7ef6934f",
"from": "0x140dd183e18ba39bd9BE82286ea2d96fdC48117A",
"to": "0x140dd183e18ba39bd9BE82286ea2d96fdC48117A",
"marketplace": "paintswap",
"price": {
"token": {
"symbol": "ftm",
"is_native": true,
"address": "0x00000000000000000000000000",
"decimal": 0
},
"amount": …
```

fix: rework twitter new sale message

---

pkg/job/update_user_roles.go

-   [x] fix update user nft role job, change return err to log err

fix: fix update user nft role job

---

migrations/schemas/20220809150330-alter_guild_config_twitter_hashtags_username.sql
migrations/schemas/20220809150352-twitter_posts.sql
pkg/entities/configs.go
pkg/entities/twitter.go
pkg/handler/twitter.go
pkg/model/guild_config_twitter_hashtag.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/twitter_post/pg.go
pkg/repo/twitter_post/store.go
pkg/request/config.go
pkg/request/twitter.go
pkg/response/config.go
pkg/routes/v1.go

- Update api `/api/v1/configs/twitter/hashtag/<guild_id>`
- New api `POST: /api/v1/twitter`
`POST: /api/v1/configs/twitter/hashtag/<guild_id>` new request sample:
```
{
"guild_id":"863278424433229854",
"user_id":"98126378126387",
"channel_id": "863278424433229858",
"rule_id":"1232131231",
"hashtag": [
"#abcd",
"#bcca",
"#cca",
"#2022"
],
"twitter_username": [
"@abc",
"@ababa"
]
}
```
`GET: /api/v1/configs/twitter/hashtag/<guild_id>` new response sample:
```
{
"data": {
"user_id": "98126378126387",
"guild_id": "863278424433229854",
"channel_id": "863278424433229858",
"rule_id":"1232131231",
"twitter_username": [
"@abc",
"@ababa"
],
"hashtag": [
"#abcd",
"#bcca",
"#cca",
"#2022"
],
"created_at": "2022-08-04T11:13:35.936322Z",
"updated_at": …
```

feat: log twitter post

---

pkg/entities/configs.go
pkg/handler/configs.go
pkg/repo/guild_config_twitter_hashtag/pg.go
pkg/repo/guild_config_twitter_hashtag/store.go
pkg/routes/v1.go

- Add API to get all twitter hashtag configs `GET: /api/v1/configs/twitter/hashtag`
Response:
```
{
"data": [
{
"user_id": "98126378126387",
"guild_id": "863278424433229854",
"channel_id": "863278424433229858",
"rule_id": "1232131231",
"twitter_username": [
"@abc",
"@ababa"
],
"hashtag": [
"#abcd",
"#bcca",
"#cca",
"#2022"
],
"created_at": "2022-08-04T11:13:35.936322Z",
"updated_at": "2022-08-09T11:30:39.303175Z"
},
{
"user_id": "98126378126387",
"guild_id": "863278424433229853",
"channel_id": "863278424433229858",
"rule_id": "1232131231",
"twitter_username": [
"@abc",
"@ababa"
],
"hashtag": [
"#abcd",
"#bcca",
"#cca",
"#2022"
],
"created_at": "2022-08-04T11:13:35.936322Z",
"updated_at": "2022-08-09T11:30:39.303175Z"
},
{
"user_id": "98126378126387",
"guild_id": …
```

chore: update twitter hashtag

---

pkg/service/cloud/cloud.go

chore: update cloud hosting

---

migrations/schemas/20220811162843-alter_mochi_nft_sales_add_pnl.sql
pkg/entities/discord_webhook.go
pkg/model/twitter.go
pkg/request/twitter.go
pkg/service/twitter/twitter.go

- Add more fields to twitter sales msg

chore: update twitter sales msg

---

pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/request/nft_collection.go
pkg/util/chain.go
pkg/util/chain_test.go

-   [x] handle get collection by address - chain

chore: handle get collection by chain

---

migrations/schemas/20220811054624-alter_guild_config_tokens_add_default.sql
pkg/chain/chain.go
pkg/entities/defi.go
pkg/entities/tokens.go
pkg/handler/configs.go
pkg/model/guild_config_token.go
pkg/repo/guild_config_token/mocks/store.go
pkg/repo/guild_config_token/pg.go
pkg/repo/guild_config_token/store.go
pkg/repo/token/mocks/store.go
pkg/repo/token/pg.go
pkg/repo/token/store.go
pkg/request/config.go
pkg/routes/v1.go

-   [x] Set default token for server
- Command: `$tokens default <symbol>`
- Example: `$tokens default eth`
**Workflow**

feat: set default token for guild

---

pkg/service/twitter/twitter.go

-   [x] Modify twitter sale message

fix: format sale message

---

go.mod
go.sum
pkg/service/cloud/cloud.go

- Fix image hosting for .webp images

chore: convert webp

---

go.mod
go.sum
pkg/service/cloud/cloud.go

Reverts consolelabs/mochi-api#249

Revert "chore: convert webp"

---

pkg/entities/tokens.go
pkg/handler/configs.go
pkg/repo/guild_config_token/mocks/store.go
pkg/repo/guild_config_token/pg.go
pkg/repo/guild_config_token/store.go
pkg/routes/v1.go

-   [x] get default token
-   [x] remove default token
- Use curl
- Get default token:
```
curl --location --request GET 'localhost:8200/api/v1/configs/tokens/default?guild_id=863338119088701470' 
```
- Get default token:
```
curl --location --request DELETE 'localhost:8200/api/v1/configs/tokens/default?guild_id=863338119088701470' 
```

feat: remove default token

---

pkg/entities/nfts.go

-  Allow query with address `/api/v1/nfts/collections/<symbol/address>/detail`

chore: update nft detail

---

pkg/entities/nfts.go
pkg/repo/nft_collection/pg.go

- nft query now returns relevant suggestions

chore: update nft suggest

---

migrations/schemas/20220817163821-guild_config_default_collection.sql
pkg/entities/configs.go
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/configs.go
pkg/handler/nfts.go
pkg/model/guild_config_default_collection.go
pkg/repo/guild_config_default_collection/pg.go
pkg/repo/guild_config_default_collection/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/nft.go
pkg/routes/v1.go

- New API  to create default symbol `POST: api/v1/configs/default-symbol`
Request body sample
```
{
"guild_id": "123121232",
"symbol": "neko",
"address": "0x1231231231234",
"chain": "ftm"
}
```
- New query params`/api/v1/nfts/<symbol>/<token_id>?guild_id=<guildID>&chain=<chain_symbol>`
- Add new field `default_symbol` to response body
Duplicated symbols with no default set
```
{
"data": {
"image_content_type": "",
"rarity_rank": 0,
"rarity_tier": "",
"attributes": null,
"rarity": null,
"metadata_id": ""
},
"suggestions": [
{
"name": "test",
"symbol": "neko",
"address": "0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE73",
"chain": "ftm"
},
{
"name": "Cryptodragonies",
"symbol": "neko",
"address": "0x0f75579F35027Cb289216a1Ee96d9dD52add4694",
"chain": "eth"
},
{
"name": …
```

feat: nft default symbol

---

pkg/entities/configs.go
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/entities/tokens.go
pkg/handler/configs.go
pkg/handler/nfts.go
pkg/repo/guild_config_default_collection/pg.go
pkg/repo/guild_config_default_collection/store.go

- `GET: /configs/tokens/?guild_id` return globally supported tokens when `guild_id=""`
- `/nfts/<symbol>/<id>?guild_id` no longer needs `chain_id`

chore: update default symbol

---

pkg/handler/default_roles.go
pkg/repo/guild_config_default_roles/pg.go

-   [x] Fix error get default role when record not found

chore: fix default role

---

pkg/entities/user.go
pkg/entities/webhook.go

-   [x] Fix error `record not found` when run command `gm`
-   [x] Fix error `Unexpected end of JSON input` when new user join server
**Description**
`Unexpected end of JSON input`: When new user join server, `userXP` will return empty struct and `user.Guild` is null. So `userXP.Guild.LogChannel` will make error.
- Errors:
- `record not found`:
- `Unexpected end of JSON input`:

fix: Unexpected end of JSON input

---

cmd/update-user-role/main.go
pkg/discordwallet/discordwallet.go
pkg/entities/configs.go
pkg/entities/configs_test.go
pkg/entities/defi.go
pkg/entities/guild.go
pkg/entities/reaction_roles.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/job/update_user_roles.go
pkg/repo/guild_config_level_role/mocks/store.go
pkg/repo/guild_config_level_role/pg.go
pkg/repo/guild_config_level_role/store.go
pkg/repo/guild_config_nft_role/pg.go
pkg/repo/guild_config_nft_role/store.go
pkg/repo/guild_config_reaction_roles/pg.go
pkg/repo/guild_config_reaction_roles/store.go
pkg/response/guild.go
pkg/service/coingecko/mocks/service.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

-   [x] Send message to log channel when updating levelrole
-   [x] Check validate roleId has been used or not when configs role
-   [x] chore: fix typo when logging
**Flow add config new role**
- Receive request and validate request 
- Check if roleID has been used for defaultrole or not
- Check if roleID has been used  for levelrole or not
- Check if roleID has been used for nftrole or not
- Check if roleID has been used for reactionrole or not
- If roleID hasn't been used, create new config for roleID
**Send embedded message when updating role**
- When update role of users based on map roleToAdd, after update role success call SendUpdateRoleMessage to send message update role to log channel
- In func SendUpdateRoleMessage: check if there is log channel ID is …

fix: update level role job

---

pkg/util/chain.go
pkg/util/marketplace.go

Update handle webhook sales event from indexer

chore: update marketplace webhook

---

pkg/entities/configs.go
pkg/entities/default_role.go
pkg/entities/reaction_roles.go
pkg/job/update_user_roles.go

-   [x] Fix catch case error record not found
-   [x] Add more log to entity layer

fix: level role config

---

migrations/schemas/20220824172003-drop_index_discord_user_gm_streaks_discord_id_uindex.sql
pkg/entities/configs.go

-   [x] Fix unique index on `discord_user_gm_streaks`
-   [x] Fix `gm` config response 
- Error unique index
- Fixed `gm` config response

fix: gm config response

---

pkg/entities/defi.go
pkg/handler/defi.go
pkg/repo/guild_config_default_ticker/pg.go
pkg/response/defi.go
pkg/service/coingecko/coingecko.go

feat: token compare suggestions

---

pkg/entities/nfts.go
pkg/model/nft_collection.go

-  Added `chain` object to `/nfts/collections/<symbol>/detail` response
New response
```
{
"data": {
"id": "d703364e-3ba6-45c5-8bc2-e4a9f46eae4a",
"address": "0x7aCeE5D0acC520faB33b3Ea25D4FEEF1FfebDE73",
"name": "neko",
"symbol": "neko",
"chain_id": 250,
"chain": {
"id": 250,
"name": "Fantom Opera",
"short_name": "ftm",
"coin_gecko_id": "fantom",
"currency": "FTM"
},
"erc_format": "721",
"is_verified": true,
"created_at": "2022-08-24T10:03:35.766676Z",
"image": "",
"author": ""
}
}
```

chore: update nft resp

---

pkg/entities/configs.go
pkg/entities/reaction_roles.go

-   [x] enhance log and error when configuring role

chore: enhance log role config

---

pkg/entities/webhook.go

chore: update gm format

---

pkg/handler/defi.go

- wrap `withdraw` api response in `data:{ }`

chore: fix withdraw res

---

pkg/entities/verification.go
pkg/handler/verification.go

Update /api/v1/verify/config/:guild_id

chore: update null verify wallet channel

---

pkg/entities/webhook.go

-   [x] Fix `gm` duration time

fix: gm duration time

---

pkg/config/config.go
pkg/entities/webhook.go
pkg/model/processor.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/service/processor/processor.go
pkg/service/processor/service.go
pkg/service/service.go

Migrate GM streak from Neko Bot:

feat: calculate user xps

---

pkg/entities/nfts.go

-   [x] Handle case no config cause index out of range
**Media**

fix: handle case no config cause index out of range

---

pkg/entities/webhook.go

Show log for gm streak 1 day
- old: not have
- new: have streak for 1 day
Ps: please ignore missing icon on local server

fix: gm streak first log

---

pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/service/marketplace/marketplace.go

- `nft add` and `nft query` API now returns code 400 for expected behaviors

chore: update nft response

---

pkg/entities/nfts.go

- Update returned error message

chore: fix error msg

---

pkg/entities/verification.go
pkg/entities/webhook.go
pkg/handler/nfts_test.go
pkg/handler/verification.go
pkg/response/verification.go

Fix some issue:
- Api get config verify channel for guild now returns 200 instead of 201
- Created verify-channel now show error
- gm allow insensitive case (Gm, gm, GM, gN, ...)

fix: minor bugs

---

pkg/repo/nft_sales_tracker/mocks/store.go
pkg/repo/nft_sales_tracker/pg.go
pkg/repo/nft_sales_tracker/store.go
pkg/response/nft_sales_tracker.go

-   [x] Add name collection and chain object in sales tracker response
**Media **

chore: add name and chains in sales tracker resp

---

pkg/entities/defi.go
pkg/response/defi.go
pkg/service/coingecko/coingecko.go

refactor: update token compare response

---

pkg/entities/sales.go
pkg/handler/nfts.go

-   [x] Check collection exist before add sale tracker
**Media**

fix: check collection exist before add sale tracker

---

migrations/schemas/20220907112719-discord_user_upvote_streaks.sql
pkg/entities/user.go
pkg/entities/webhook.go
pkg/handler/users.go
pkg/handler/webhook.go
pkg/model/discord_user_upvote_streak.go
pkg/repo/discord_user_upvote_streak/pg.go
pkg/repo/discord_user_upvote_streak/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/webhook.go
pkg/response/user.go
pkg/routes/v1.go

-  Webhooks for external app to call to `/webhook/topgg` and `/webhook/discordbotlist`
- Upvote streak expire after 13 hours ( user can upvote every 12hr )
- API to get users upvote streak:
`curl --location --request GET 'http://localhost:8200/api/v1/users/upvote-streak?discord_id=319132138849173505'`
Response:
```
{
"data": {
"discord_id": "319132138849173505",
"minutes_until_reset": 780,        -> this will be 0 if ran out of time
"streak_count": 1,
"total_count": 5,
"last_streak_time": "2022-09-07T18:00:00Z"
}
}
```

feat: upvote streak

---

migrations/schemas/20220907131515-user-watchlist.sql
pkg/entities/defi.go
pkg/handler/defi.go
pkg/model/user_watchlist_item.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_watchlist_item/pg.go
pkg/repo/user_watchlist_item/store.go
pkg/request/config.go
pkg/request/defi.go
pkg/response/defi.go
pkg/routes/v1.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

feat: watchlist APIs

---

pkg/model/discord_guild_stat.go
pkg/model/discord_guild_stat_channel.go
pkg/model/guild_config_default_role.go
pkg/model/guild_config_gm_gn.go
pkg/model/guild_config_invite_tracker.go
pkg/model/guild_config_nft_role.go
pkg/model/guild_config_reaction_roles.go
pkg/model/guild_config_repostable_reaction.go
pkg/model/guild_config_sales_tracker.go
pkg/model/guild_user.go
pkg/model/invite_history.go
pkg/model/message_repost_history.go
pkg/model/nft_collection.go
pkg/model/nft_sales_tracker.go
pkg/model/twitter.go
pkg/model/user_nft_balance.go
pkg/response/nft_sales_tracker.go

-   [x] chore: add swagger type tag

chore: add swagger type tag

---

pkg/entities/webhook.go

- gm/gn now response at 1st and 2nd streak

chore: update gm response

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
go.sum
migrations/schemas/20220830171900-create_guild_config_group_nft_roles.sql.sql
migrations/test_seed/guild_config_nft_roles.yml
pkg/entities/configs.go
pkg/handler/configs.go
pkg/handler/configs_test.go
pkg/job/update_user_roles.go
pkg/model/guild_config_group_nft_role.go
pkg/model/guild_config_nft_role.go
pkg/model/user_nft_balance.go
pkg/repo/guild_config_group_nft_role/pg.go
pkg/repo/guild_config_group_nft_role/store.go
pkg/repo/guild_config_nft_role/pg.go
pkg/repo/guild_config_nft_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_nft_balance/pg.go
pkg/repo/user_nft_balance/store.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

Todo:
create config: POST `/api/v1/configs/nft-roles` 
get config by guild: GET `/api/v1/configs/nft-roles`
remove collections from group: DELETE `api/v1/configs/nft-roles`. Ex: remove collection A,B from group config A,B,C,D,E
query params: config_ids = `242f9d1c-ecfa-40ca-86db-726f0458fd1a|3875629b-6135-4fdd-bdc8-fe98ee341caf`
remove group config: DELETE `/api/v1/configs/nft-roles`

feat: migrate db

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user.go
pkg/handler/users.go
pkg/response/user.go
pkg/routes/v1.go

- Fix return null when not have streak
- Wrap response swagger in data

fix; upvote streak resp

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/defi.go

-   [x] Update swagger for watchlist APIs

chore: update swagger - watchlist

---

migrations/schemas/20220907223724-upvote_streak_tiers.sql
migrations/seed/seed.sql
migrations/seed/upvote_streak_tiers.sql
pkg/entities/webhook.go
pkg/model/upvote_streak_tier.go
pkg/repo/guild_user_activity_log/pg.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/upvote_streak_tiers/pg.go
pkg/repo/upvote_streak_tiers/store.go

- Add upvote tiers bonus
Feature flow: User upvotes -> Add to streak and total count accordingly -> Get current streak tier -> Log upvote activity -> **To do:** recreate user xp view 
Upvote activity in log
Upvote streak tiers

feat: log upvote activity

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/configs.go
pkg/handler/configs.go
pkg/repo/upvote_streak_tiers/pg.go
pkg/repo/upvote_streak_tiers/store.go
pkg/response/config.go
pkg/routes/v1.go

- API to get upvote streak tiers 
```
curl --location --request GET 'http://localhost:8200/api/v1/configs/upvote-tiers' \
{
"message": "OK",
"data": [
{
"id": 1,
"streak_required": 0,
"xp_per_interval": 20,
"vote_interval": 4
},
{
"id": 2,
"streak_required": 2,
"xp_per_interval": 30,
"vote_interval": 4
},
{
"id": 3,
"streak_required": 4,
"xp_per_interval": 30,
"vote_interval": 3
},
{
"id": 4,
"streak_required": 6,
"xp_per_interval": 40,
"vote_interval": 3
},
{
"id": 5,
"streak_required": 8,
"xp_per_interval": 40,
"vote_interval": 2
}
]
}
```

feat: upvote api

---

pkg/entities/configs.go
pkg/job/update_user_roles.go
pkg/model/guild_config_nft_role.go
pkg/repo/guild_config_nft_role/pg.go
pkg/repo/user_nft_balance/pg.go
pkg/repo/user_nft_balance/store.go

https://www.loom.com/share/91f2556fe5ee4edebde7238787c412d5

fix: perf nft role

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/defi.go
pkg/model/pagination.go
pkg/repo/user_watchlist_item/pg.go
pkg/repo/user_watchlist_item/store.go
pkg/response/defi.go
pkg/response/pagination.go

-   [x] Add pagination to `[GET] /watchlist` response

refactor: watchlist pagination response

---

migrations/schemas/20220910153342-discord_user_upvote_log.sql
pkg/consts/discord.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/handler/nfts.go
pkg/handler/webhook.go
pkg/model/discord_user_upvote_log.go
pkg/repo/discord_user_upvote_log/pg.go
pkg/repo/discord_user_upvote_log/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/user.go
pkg/util/util.go

- Add upvote log to get time left for each upvote source
- `nft/new-listed` now returns null and code 200 if `record not found`
- New `users/upvote-streak` response
```
{
"data": {
"discord_id": "319132138849173505",
"minutes_until_reset": 780,
"minutes_until_reset_topgg": 780,
"minutes_until_reset_discordbotlist": 780,
"streak_count": 7,
"total_count": 22,
"last_streak_time": "2022-09-12T10:33:00Z"
}
}
```

feat: add upvote log

---

pkg/entities/defi.go

-   [x] Return default watchlist if user's contains no item

feat: default watchlist

---

cmd/fetch-coingecko-tokens/main.go
migrations/schemas/20220913160530-add_supported_coingecko_tokens.sql
pkg/entities/defi.go
pkg/job/fetch_coingecko_coins.go
pkg/model/coingecko_supported_tokens.go
pkg/repo/coingecko_supported_tokens/pg.go
pkg/repo/coingecko_supported_tokens/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/defi.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

feat: fetch coingecko supported job

---

pkg/entities/webhook.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- Add server link to new guild notification
- Update new upvote msg
Upvote message for unknown users
Link to new server

chore: update notify msg

---

pkg/entities/defi.go
pkg/handler/defi.go
pkg/model/errors/base.go
pkg/model/errors/error.go
pkg/repo/user_watchlist_item/pg.go
pkg/repo/user_watchlist_item/store.go

-   [x] watchlist: return correct error message and status code for specific errors

fix: watchlist specific errors code

---

pkg/handler/webhook.go
pkg/response/invite_history.go

-   [x] fix: invitee is bot
**Description**
- function `h.entities.FindInviter` cannot find inviter profile if admin add bot to server
- invite bot to server
Error:

fix: invitee is bot

---

pkg/service/discord/discord.go

Show number of members when bot joins new server

chore: add count member guild

---

pkg/service/discord/discord.go

Update new format for notify new guild

chore: update notify new guild

---

pkg/repo/token/pg.go

-   [x] Add order by ID when query supported tokens

chore: add order by id

---

pkg/service/discord/discord.go
pkg/util/discord.go

- Update invite link to non-expire one

chore: upvite invite link

---

cmd/update-gm-streak/main.go
cmd/update-upvote-streak/main.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/job/update_gm_streak.go
pkg/job/update_upvote_streak.go
pkg/repo/discord_user_gm_streak/pg.go
pkg/repo/discord_user_gm_streak/store.go
pkg/repo/discord_user_upvote_streak/pg.go
pkg/repo/discord_user_upvote_streak/store.go

- Add cronjob to update gm and upvote streak, reset streak count to 0 if past 24h since last time
After update

chore: update streak job

---

pkg/handler/webhook.go

-   [x] Check error missing permission for guild add member API
** Media **

chore: check error missing permission

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/nfts.go
pkg/response/nft.go

Wrap api `nft integrate` in data

fix: nft integrate resp

---

pkg/entities/webhook.go
pkg/request/processor.go
pkg/service/processor/mocks/service.go
pkg/service/processor/processor.go
pkg/service/processor/service.go

- Upvote webhook call to processor API to handle faction xp bonus

chore: handle upvote xp

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20220919165929-alter_users_add_nr_of_join.sql.sql
pkg/entities/user.go
pkg/handler/users.go
pkg/model/user.go
pkg/repo/users/pg.go
pkg/repo/users/store.go
pkg/response/user.go

Demo: 
https://www.loom.com/share/e43f473b58454206a53caca4ebf422db

feat: user join server

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user.go
pkg/handler/users.go
pkg/repo/discord_user_upvote_streak/pg.go
pkg/repo/discord_user_upvote_streak/store.go
pkg/response/user.go
pkg/routes/v1.go

- Add API to get top upvote users by streak count or total count

feat: vote leaderboard

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20220920133951-guild_config_vote_channels.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_config_vote_channel.go
pkg/repo/guild_config_vote_channel/pg.go
pkg/repo/guild_config_vote_channel/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

- Add APIs to config vote channel
`GET` and `POST` response

feat: vote config

---

pkg/entities/user.go
pkg/handler/webhook.go

-   [x] fix: deleted account response
-  Create invite link and delete account, api cannot find the inviter by code

fix: deleted account response

---

migrations/schemas/20220920152201-servers-usage-stats.sql
pkg/entities/servers_usage_stats.go
pkg/handler/servers_usage_stats.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/servers_usage_stats/pg.go
pkg/repo/servers_usage_stats/store.go
pkg/request/servers_usage_stats.go
pkg/routes/v1.go

-   [x] API for send usage stats

feat: api for store servers usage stats

---

pkg/service/discord/discord.go

chore: gm streak notification format

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user.go
pkg/handler/users.go
pkg/repo/discord_user_upvote_streak/pg.go
pkg/repo/discord_user_upvote_streak/store.go

- add query `guild_id` to upvote leaderboard api

chore: update vote ldb

---

migrations/schemas/20220920190013-alter_servers_usage_stats.sql
pkg/entities/servers_usage_stats.go
pkg/model/servers_usage_stats.go
pkg/repo/servers_usage_stats/pg.go
pkg/repo/servers_usage_stats/store.go

-   [x] Add field created_at for usage stats

fix: add created at field

---

pkg/entities/webhook.go

- Upvote xp now increase by tiers

chore: update vote

---

pkg/entities/user.go

-   [x] Edit to zero gm streak
Before: 
After:

fix: edit zero gm streak

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/defi.go

-   [x] Update token comparison API: `guild_id` is no more required

fix: token comparison

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/response/nft_collection.go

-   [x] Edit nft list command response

chore: edit nft list response

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml

chore: update docs

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/configs.go

- Fixed `whitelist-prune` swagger type

chore: fix swagger type

---

pkg/entities/user.go

- Update vote expire time to 12h instead of 13h

chore: update vote time

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/reaction_roles.go
pkg/handler/reaction_roles.go
pkg/repo/guild_config_reaction_roles/pg.go
pkg/response/role_reaction_config.go

- Fix api return 500 not found. When user add emoji which is not config in reaction role -> return null with status 200
- Wrap data response in `data`
- Update `$rr add` to `$rr set`

refactor: rr flow

---

migrations/schemas/20220926182944-message-reactions.sql
pkg/entities/configs.go
pkg/entities/message_reaction.go
pkg/entities/message_repost_history.go
pkg/entities/webhook.go
pkg/handler/webhook.go
pkg/handler/webhook_test.go
pkg/model/message_reaction.go
pkg/repo/guild_config_repost_reaction/pg.go
pkg/repo/message_reaction/pg.go
pkg/repo/message_reaction/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/message_reaction.go
pkg/request/webhook.go

-   [x] feat: add event message delete
-   [x] chore: move reaction roles logic from bot to api
**Affected features**
- Config reaction roles
- Add/Remove role when react
- Starboard
- Reaction role
https://user-images.githubusercontent.com/104887632/192351178-922c244c-b2b8-4969-a763-c4ff02e4219a.mp4
- Starboard
https://user-images.githubusercontent.com/104887632/192433637-7e9107d4-5cb8-434f-bd99-072317cd25cf.mp4

feat: add event message delete

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20220927172540-create-user-nft-watchlist-items.sql.sql
pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/model/user_nft_watchlist_item.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_nft_watchlist_items/pg.go
pkg/repo/user_nft_watchlist_items/store.go
pkg/request/nft.go
pkg/response/nft.go
pkg/routes/v1.go
pkg/service/indexer/indexer.go
pkg/service/indexer/mocks/service.go
pkg/service/indexer/service.go

Currently using response like `$wl` so maybe not follow standard
- Remove
- Get: Mock data. If collection not have snapshot -> price = [] other wise price = []float64{}
- Add
1. If pass Symbol with 1 result and no suggestion -> create record in db
2. If pass Symbol with duplicate collection and many suggestions -> show list suggestion
Now bot will call api 1 more time with passing collection_address + chain
-> Now will create record in db

feat: nft watchlist

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/defi_test.go
pkg/handler/testdata/get_coin/200-success-eth.json
pkg/response/defi.go

-   [x] Add field description for token info cmd

feat: Add field description for token info cmd

---

pkg/response/response.go

-   [x] chore: update response structure

chore: update response structure

---

pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/response/nft.go

When token not found return 200 with `data: null`

fix: status nft query

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/repo/user_nft_watchlist_items/store.go

fix: nft wl

---

migrations/schemas/20220928170237-create-offchain_tip_bot-tables.sql

-   [x] add offchain_tip_bot tables

feat: add offchain_tip_bot tables

---

pkg/handler/defi.go
pkg/handler/nfts.go

wrap response for `/defi, /nft`

chore: validate resp

---

pkg/handler/configs.go
pkg/handler/guilds.go
pkg/handler/invites.go
pkg/handler/nfts.go
pkg/handler/users.go

-   [x] chore: wrap response for community
**Affected features**
- gm
- invite
- prune
- sales
- verify
- vote
- stats
- top

chore: wrap response for community

---

pkg/handler/configs.go
pkg/handler/default_roles.go
pkg/handler/guilds.go

-   [x] Wrap config response
**Feature affected:**
- default role
- nft role
- log
- welcome
- starboard

chore: wrap config response

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/guild.go
pkg/entities/message_reaction.go
pkg/entities/webhook.go
pkg/handler/chain.go
pkg/handler/custom_command.go
pkg/handler/guilds.go
pkg/handler/users.go
pkg/handler/verification.go
pkg/handler/webhook.go
pkg/response/guild.go

-   [x] chore: wrap response for common command
**Affected features**
- guild's api
- user's api
- webhook's api

chore: wrap response for common command

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nfts.go
pkg/handler/sales.go
pkg/handler/testdata/create_nft_collection/400-insync.json
pkg/handler/testdata/create_nft_collection/400-not-sync.json
pkg/handler/testdata/create_nft_collection/500-cannot-find-contract.json
pkg/handler/users.go
pkg/response/nft_collection.go

- Fix `$nft recent`
- Wrap response

chore: update response

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/configs.go
pkg/entities/default_role.go
pkg/entities/defi.go
pkg/handler/configs.go
pkg/handler/custom_token.go
pkg/handler/default_roles.go
pkg/handler/defi.go
pkg/response/config.go
pkg/response/default_role.go

-   [x] chore: wrap response in config
**Affected features**
- config's apis

chore: wrap response in config

---

pkg/handler/users.go

fix: status code

---

pkg/entities/defi.go
pkg/handler/defi.go
pkg/response/defi.go

- Wrap API response in correct format

chore: wrap response defi

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/response/nft.go
pkg/service/indexer/indexer.go
pkg/service/indexer/mocks/service.go
pkg/service/indexer/service.go

chore: nft collection info

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/response/nft.go

chore: marketplace in collection metadata

---

pkg/entities/configs_test.go
pkg/handler/configs_test.go
pkg/handler/custom_token_test.go
pkg/handler/testdata/custom-token/500-chain-not-found.json
pkg/handler/testdata/custom-token/500-coin-not-found.json
pkg/handler/testdata/custom-token/500-coin-not-supported.json

- tests for `$token`: `list, add, remove, add-custom`

chore: test token

---

migrations/test_seed/discord_user_upvote_streaks.yml
pkg/handler/testdata/users/200-vote-top-streak.json
pkg/handler/testdata/users/200-vote-top-total.json
pkg/handler/users_test.go

chore: test vote top

---

migrations/test_seed/guild_user_activity_logs.yml
pkg/entities/nfts.go
pkg/entities/user_test.go
pkg/handler/nfts.go
pkg/handler/testdata/400-missing-userID.json
pkg/handler/testdata/users/200-top-users.json
pkg/handler/testdata/users/200-user-profiles.json
pkg/handler/users_test.go
pkg/response/nft.go
pkg/service/indexer/indexer.go

test: profiles

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/handler/nfts.go
pkg/request/nft.go
pkg/response/nft.go
pkg/routes/v1.go
pkg/service/indexer/indexer.go
pkg/service/indexer/mocks/service.go
pkg/service/indexer/service.go

+ Show basic info of token instead of collection. Ex: token name, token image, token rank, ...
+ Not have total volume

feat: ticker nft token

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/response/nft.go

chore: floor price nft detail

---

migrations/schemas/20221012143416-alter_guild_config_repost_reaction_add_start_stop.sql
pkg/entities/configs.go
pkg/entities/message_repost_history.go
pkg/handler/testdata/guild_config_repost_reactions/200-exist-guild-config-repost-reaction.json
pkg/model/guild_config_repostable_reaction.go
pkg/model/message_repost_history.go
pkg/repo/guild_config_repost_reaction/mocks/store.go
pkg/repo/guild_config_repost_reaction/pg.go
pkg/repo/guild_config_repost_reaction/store.go
pkg/request/message_reaction.go

TODO: implement config start, stop
https://www.notion.so/console-labs/sb-start-stop-c92054fc5ae34438ba2547d94988ed08
- Not have start, stop config
https://www.loom.com/share/6de2aeb0129b44c995f8a324d5d129be
- Has start, stop config
https://www.loom.com/share/993a29aebbf14935b2baa922f304b5c7

feat: sb start stop

---

pkg/entities/nfts.go

- Rcm collection in `$nft ticker` not follow `$nft query + $wl add-nft`
- Old vs New

fix: logic rcm collections ticker

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221013173121-add_bonus_quest.sql
pkg/entities/quest.go
pkg/model/quest.go
pkg/repo/quest/pg.go
pkg/repo/quest/query.go

**Background**
- Bonus quest is also a type of quests
- Bonus quest is a quest that will give users extra rewards when they complete an amount (`frequency`) of quests
1. if quest is completed, update `current` of bonus quest
-> then execute logic like other quests (if `current` == `target` then user can claim the bonus rewards)
2. if quest is not completed, do nothing
_Note_: Bonus quest cannot be updated from outside

feat: bonus quest

---

pkg/entities/message_reaction.go
pkg/entities/message_repost_history.go
pkg/handler/webhook.go

-   [x] chore: reduce reaction number when remove reaction
[Screencast from 14-10-2022 21:10:38.webm](https://user-images.githubusercontent.com/104887632/195868132-278b7bff-f805-419b-8078-c4dfa06f9489.webm)

chore: reduce reaction number when remove reaction

---

pkg/entities/defi.go
pkg/entities/quest.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/handler/defi.go
pkg/model/quest.go
pkg/repo/quest/pg.go
pkg/repo/quest_user_list/pg.go
pkg/repo/quest_user_list/query.go
pkg/request/defi.go

fix: quests

---

migrations/schemas/20221014113257-alter_servers_usage_stats_success.sql
pkg/entities/servers_usage_stats.go
pkg/model/servers_usage_stats.go
pkg/request/servers_usage_stats.go

- add field `success` to usage log

chore: log usage

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221017163901-alter_discord_guilds.sql
pkg/entities/guild.go
pkg/model/discord_guild.go
pkg/repo/discord_guilds/pg.go
pkg/request/guild.go

-   [x] Add left date filed for discord guild
Add and kick bot 

feat: collect join and left date of guild

---

migrations/schemas/20221014113257-alter_servers_usage_stats_success.sql
migrations/schemas/20221017124102-alter_servers_usage_stats_response_time.sql
pkg/entities/servers_usage_stats.go
pkg/model/servers_usage_stats.go
pkg/request/servers_usage_stats.go

- add new field `execution_time_ms` to `servers_usage_stats` table

chore: benchmark cmd

---

pkg/entities/configs.go
pkg/entities/configs_test.go
pkg/handler/configs.go
pkg/handler/repost_reaction_test.go
pkg/repo/guild_config_repost_reaction/mocks/store.go
pkg/repo/guild_config_repost_reaction/pg.go
pkg/repo/guild_config_repost_reaction/store.go

-   [x] chore: get repost config by query
https://www.loom.com/share/ffc95d47cdd9483d8c9a5da92de953e7

chore: get repost config by query

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221018113141-guild_config_join_leave_channel.sql
pkg/entities/configs.go
pkg/entities/webhook.go
pkg/handler/configs.go
pkg/handler/webhook.go
pkg/model/guild_config_join_leave_channel.go
pkg/repo/guild_config_join_leave_channel/pg.go
pkg/repo/guild_config_join_leave_channel/store.go
pkg/repo/pg/repo.go
pkg/repo/quest/mocks/store.go
pkg/repo/repo.go
pkg/request/config.go
pkg/request/webhook.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/util/util.go

- API to config join-leave monitoring channel
- New webhook event `guildMemberRemove`
- Event `guildMemberRemove` and `guildMemberAdd` send notification to join-leave channel if exists

feat: joinleave server

---

migrations/schemas/20221018135422-gitbook_click_collector.sql
pkg/entities/servers_usage_stats.go
pkg/handler/servers_usage_stats.go
pkg/model/gitbook_click_collectors.go
pkg/repo/gitbook_click_collectors/pg.go
pkg/repo/gitbook_click_collectors/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/routes/v1.go

-   [x] Collect gitbook click 
click on gitbook link in help message

feat: add collect gitbook click

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/config/config.go
pkg/entities/feedback.go
pkg/handler/feedback.go
pkg/request/feedback.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- API for feedback and post to a feedback channel
- Feedback maybe about a specific command or not

feat: feedback

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/configs.go
pkg/entities/configs_test.go
pkg/handler/configs.go
pkg/repo/guild_config_repost_reaction/mocks/store.go
pkg/repo/guild_config_repost_reaction/pg.go
pkg/repo/guild_config_repost_reaction/store.go
pkg/routes/v1.go

-   [x] Sb remove conversation config

feat: sb remove conversation

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221020121253-create-trade-offers-and-trade-items-table.sql
pkg/entities/trade.go
pkg/handler/trade.go
pkg/model/trade_item.go
pkg/model/trade_offer.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/trade_item/pg.go
pkg/repo/trade_item/store.go
pkg/repo/trade_offer/pg.go
pkg/repo/trade_offer/store.go
pkg/request/trade.go
pkg/response/trade.go
pkg/routes/v1.go

-   [x] Create trade offer
-   [x] Get trade offer by id
- Create
```bash
curl -X 'POST' \
'http://localhost:8200/api/v1/trades' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"from_address": "0x5417A03667AbB6A059b3F174c1F67b1E83753046",
"from_items": [
{
"token_address": "0x5417A03667AbB6A059b3F174c1F67b1E83753046",
"token_ids": [
"1", "2", "3"
]
}
],
"to_address": "0xAEeE56fe367381f29510C27F1Dae815E9591d60a",
"to_items": [
{
"token_address": "0xAEeE56fe367381f29510C27F1Dae815E9591d60a",
"token_ids": [
"4", "5", "6"
]
}
]
}'
```
- Get
```Bash
'http://localhost:8200/api/v1/trades/{created_id}' \
```

feat: trade offer

---

pkg/service/discord/discord.go

- update color for join-leave message

chore: update joinleave

---

migrations/schemas/20221021113958-guild_blacklist_channel_repost_configs.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_blacklist_channel_repost_configs.go
pkg/repo/guild_blacklist_channel_repost_configs/pg.go
pkg/repo/guild_blacklist_channel_repost_configs/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/routes/v1.go

-   [x] sb blacklist channel repost

feat: sb blacklist channel repost

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/configs.go
pkg/handler/offchain_tip_bot.go
pkg/response/offchain_tip_bot_withdraw.go
pkg/routes/v1.go

-   [x] Mock off chain tip bot withdraw api

chore: mock withdraw api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221021122015-alter_offchain_tip_bot_activity_logs.sql
pkg/consts/offchain_tip_bot.go
pkg/entities/offchain_tip_bot.go
pkg/entities/offchain_tip_bot_contract.go
pkg/handler/offchain_tip_bot.go
pkg/model/offchain_tip_bot_activity_log.go
pkg/model/offchain_tip_bot_transfer_history.go
pkg/model/offchain_tip_bot_user_balance.go
pkg/repo/offchain_tip_bot_activity_logs/repo.go
pkg/repo/offchain_tip_bot_activity_logs/store.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go
pkg/repo/offchain_tip_bot_transfer_histories/pg.go
pkg/repo/offchain_tip_bot_transfer_histories/store.go
pkg/repo/offchain_tip_bot_user_balances/pg.go
pkg/repo/offchain_tip_bot_user_balances/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/offchain_tip_bot.go
pkg/response/offchain_tip_bot.go
pkg/routes/v1.go

- success
- token not sp
- not enough bals

feat: transfer token

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221024153846-add_twitter_blacklist.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_config_twitter_blacklist.go
pkg/repo/guild_config_twitter_blacklist/pg.go
pkg/repo/guild_config_twitter_blacklist/query.go
pkg/repo/guild_config_twitter_blacklist/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/twitter.go
pkg/response/config.go
pkg/routes/v1.go

-   [x] twitter blacklist APIs (get list, add, remove)
1. `[GET] /api/v1/configs/twitter/blacklist`
2. `[POST /api/v1/configs/twitter/blacklist`
3. `[DELETE] /api/v1/configs/twitter/blacklist`

feat: twitter blacklist APIs

---

pkg/entities/offchain_tip_bot.go

-   [x] Handle case tip all token for offchain
$tip @hoangharry all cake 
https://www.loom.com/share/222b2a369e704c57a42e7651c29ff46f

feat: handle case tip all for offchain

---

pkg/chain/chain.go
pkg/config/config.go
pkg/discordwallet/discordwallet.go
pkg/entities/defi.go
pkg/entities/offchain_tip_bot.go

refactor: wd offchain use private key

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221031105524-discord_user_devices.sql
migrations/schemas/20221031105530-discord_user_token_alert.sql
pkg/entities/configs.go
pkg/entities/user.go
pkg/handler/configs.go
pkg/handler/users.go
pkg/model/discord_user_device.go
pkg/model/discord_user_token_alert.go
pkg/repo/discord_user_device/pg.go
pkg/repo/discord_user_device/store.go
pkg/repo/discord_user_token_alert/pg.go
pkg/repo/discord_user_token_alert/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/alert.go
pkg/response/alert.go
pkg/routes/v1.go

API for
**Token Alert**
**User Device**

feat: alert widget

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/configs.go
pkg/repo/discord_user_token_alert/pg.go
pkg/request/alert.go

- changed token-alert DELETE api query to `id`

chore: update alert api

---

migrations/schemas/20221101112946-alter_offchain_tip_bot_tokens.sql
pkg/entities/offchain_tip_bot_contract.go
pkg/model/offchain_tip_bot_token.go

-   [x] Add coingeckoid for offchain token

feat: add congeckoid for offchain token

---

pkg/entities/offchain_tip_bot.go
pkg/entities/offchain_tip_bot_contract.go
pkg/response/offchain_tip_bot.go

-   [x] Add rate in usd field for balance
-  [x] Add amount in usd for tip

chore: get price in usd for tip and bal

---

pkg/entities/user.go
pkg/handler/users.go
pkg/response/user.go
pkg/routes/v1.go

-   [x] Add api get user_wallet from mochi by guildID - wallet

chore: add new api for get user wallet by guildID and address

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot_transfer_histories.go
pkg/handler/offchain_tip_bot_transfer_histories.go
pkg/repo/offchain_tip_bot_transfer_histories/pg.go
pkg/repo/offchain_tip_bot_transfer_histories/store.go
pkg/response/offchain_tip_bot.go
pkg/routes/v1.go

feat: user tx

---

pkg/service/discord/discord.go

fix: gm streak message emoji

---

pkg/entities/offchain_tip_bot.go
pkg/handler/offchain_tip_bot.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go
pkg/repo/offchain_tip_bot_user_balances/pg.go
pkg/repo/offchain_tip_bot_user_balances/store.go
pkg/response/offchain_tip_bot.go
pkg/routes/v1.go

feat: check bals offchain and onchain

---

migrations/schemas/20221103135425-alter_offchain_tip_bot_tokens.sql
pkg/entities/offchain_tip_bot.go
pkg/handler/offchain_tip_bot.go
pkg/model/offchain_tip_bot_activity_log.go
pkg/model/offchain_tip_bot_token.go
pkg/model/offchain_tip_bot_transfer_history.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go
pkg/repo/offchain_tip_bot_transfer_histories/pg.go
pkg/repo/offchain_tip_bot_transfer_histories/store.go
pkg/request/offchain_tip_bot.go
pkg/response/offchain_tip_bot.go
pkg/routes/v1.go

These api are used for setup dashboard (internal use), temp not gen swagger for it

feat: apply fee for withdraw

---

pkg/entities/feedback.go
pkg/repo/user_feedback/pg.go
pkg/repo/user_feedback/store.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- Add confirm button to feedback message
- Set button custom-id to feedback's uuid

chore: update feedback

---

pkg/handler/feedback.go
pkg/service/discord/discord.go

-   [x] Small tweaks to the feedback button

chore: tweak feedback button

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/feedback.go

- set `filter` and `value` of feedback API to "not required"

chore: update feedback swagger

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/defi.go
pkg/handler/testdata/user_watchlist/get-200-ok-custom.json
pkg/handler/testdata/user_watchlist/get-200-ok-default.json
pkg/response/defi.go
pkg/util/testhelper/model_util.go

-   [x] default flag to know if response data is user's watchlist or default on

feat: wl - default flag

---

pkg/entities/nfts.go

-   [x] skip get info of collection when not existing in paintswap

chore: skip get info of collection when not existing in paintswap

---

pkg/entities/nfts.go
pkg/repo/nft_sales_tracker/mocks/store.go
pkg/repo/nft_sales_tracker/pg.go
pkg/repo/nft_sales_tracker/store.go

- Temporarily display * tracker for tracking all nft collections

chore: update-sales

---

pkg/entities/webhook.go

-   [x] Use whoop whoop sticker as gm

feat: use whoop whoop sticker as gm

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221117150510-alter_user_watchlist_item_isfiat.sql
pkg/entities/defi.go
pkg/model/user_watchlist_item.go
pkg/request/defi.go
pkg/response/fiat.go
pkg/service/nghenhan/nghenhan.go
pkg/service/nghenhan/service.go
pkg/service/service.go

- New service from nghenhan API
- Add field `is_fiat` to `user_watchlist_items`

chore: wl fiat

---

pkg/entities/configs.go
pkg/repo/discord_user_token_alert/pg.go
pkg/repo/discord_user_token_alert/store.go
pkg/request/alert.go
pkg/util/util.go

- `POST configs/token-alert` can update existing records if provided with `id` in request body

chore: update token alert

---

pkg/service/discord/discord.go

-   [x] Fix the id to match with bot button handler id

fix: button handle feedback id

---

pkg/entities/defi.go
pkg/service/nghenhan/nghenhan.go

- Added support for fiat ticker with non-USD base

chore: update fiat service

---

.githooks/pre-commit
Makefile
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/guild.go
pkg/entities/nfts.go
pkg/entities/user.go
pkg/handler/metric.go
pkg/repo/nft_collection/mocks/store.go
pkg/repo/nft_collection/pg.go
pkg/repo/nft_collection/store.go
pkg/response/metric.go
pkg/routes/v1.go

feat: three first metrics

---

pkg/entities/defi.go
pkg/service/nghenhan/nghenhan.go

-> Filter response data from nghenhan

fix: fiat chart - filter time range

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/servers_usage_stats.go
pkg/entities/tokens.go
pkg/entities/tokens_test.go
pkg/entities/user.go
pkg/handler/metric.go
pkg/repo/discord_wallet_verification/pg.go
pkg/repo/discord_wallet_verification/store.go
pkg/repo/servers_usage_stats/pg.go
pkg/repo/servers_usage_stats/store.go
pkg/repo/token/mocks/store.go
pkg/repo/token/pg.go
pkg/repo/token/store.go
pkg/response/metric.go

feat: three last metrics

---

pkg/entities/configs.go
pkg/job/push_noti_widget.go
pkg/repo/discord_user_token_alert/pg.go
pkg/repo/discord_user_token_alert/store.go
pkg/service/apns/apns.go
pkg/service/apns/service.go

- Fix correct APNS topic
- Disable alert after notify

chore: update widget alert

---

migrations/schemas/20221124150240-alter_user_nft_balances_add_staking_nekos.sql
pkg/repo/user_nft_balance/pg.go

feat: count staking neko

---

pkg/cache/cache.go
pkg/cache/redis.go
pkg/entities/cache.go
pkg/entities/configs.go
pkg/job/push_noti_widget.go
pkg/model/discord_user_token_alert.go
pkg/repo/discord_user_token_alert/pg.go
pkg/repo/discord_user_token_alert/store.go

-  Save new token alerts to Redis

chore: update ws noti

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221125110708-guild_config_default_currencies.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/model/guild_config_default_currency.go
pkg/repo/guild_config_default_currency/pg.go
pkg/repo/guild_config_default_currency/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/common.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

- Guild default currency API (get, upsert, delete)

chore: guild default currency

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221124113152-more_twitter_stats.sql
pkg/entities/twitter.go
pkg/handler/twitter.go
pkg/model/twitter_post.go
pkg/model/twitter_post_streak.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/twitter_post/pg.go
pkg/repo/twitter_post/store.go
pkg/repo/twitter_post_streak/pg.go
pkg/repo/twitter_post_streak/query.go
pkg/repo/twitter_post_streak/store.go
pkg/request/twitter.go
pkg/response/twitter.go
pkg/routes/v1.go

feat: twitter leaderboard

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221125174203-alter_discord_user_token_alerts_symbol.sql
pkg/entities/configs.go
pkg/handler/configs.go
pkg/job/push_noti_widget.go
pkg/model/discord_user_token_alert.go
pkg/repo/discord_user_token_alert/pg.go
pkg/request/alert.go

- add `symbol` to `discord_user_token_alerts`

chore: update alert

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot_transfer_histories.go
pkg/handler/offchain_tip_bot_transfer_histories.go
pkg/repo/offchain_tip_bot_transfer_histories/mocks/store.go
pkg/repo/offchain_tip_bot_transfer_histories/pg.go
pkg/repo/offchain_tip_bot_transfer_histories/store.go
pkg/response/offchain_tip_bot_tranfer_histories.go

-   [x] Handle case list statements of all tokens and remove unnecessary field in statement api  

chore: edit statement cmd api

---

pkg/entities/configs.go

chore: fix alert

---

migrations/schemas/20221129132206-create-offchain-tip-bot-config-notify.sql
pkg/consts/offchain_tip_bot.go
pkg/entities/offchain_tip_bot.go
pkg/model/offchain_tip_bot_config_notify.go
pkg/repo/offchain_tip_bot_config_notify/pg.go
pkg/repo/offchain_tip_bot_config_notify/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go

feat: notify tip log channel

---

pkg/job/push_noti_widget.go
pkg/service/apns/apns.go
pkg/service/apns/service.go

- add more detailed logging to `push-noti-widget`

chore: update alert log

---

pkg/service/apns/apns.go

-   [x] Add title, sound, format price to notification payload

fix: decorate push notification

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/response/nft_collection.go

chore: nft stat all chain

---

pkg/job/push_noti_widget.go

chore: fix widget

---

pkg/entities/configs.go
pkg/entities/configs_test.go
pkg/entities/offchain_tip_bot_chain.go
pkg/entities/tokens.go
pkg/handler/configs.go
pkg/handler/offchain_tip_bot.go
pkg/handler/repost_reaction_test.go

-   [x] fix: 404 status for some APIs

fix: add 404 status for some APIs

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20221205164015-alter-offchain-tip-bot-activity-logs.sql
pkg/entities/offchain_tip_bot.go
pkg/model/offchain_tip_bot_activity_log.go
pkg/request/offchain_tip_bot.go
pkg/service/coingecko/coingecko.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

-   [x] send tip log with image and message tip

chore: send tip log with image and message tip

---

pkg/entities/offchain_tip_bot.go
pkg/service/discord/discord.go

-   [x] edit log tip msg move to footer

chore: edit log tip msg

---

pkg/service/discord/discord.go

-   [x]remove emoji footer tip log

chore: remove emoji footer tip log

---

pkg/entities/data_webhook.go
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/data_webhook.go
pkg/handler/nfts_test.go
pkg/request/data_webhook.go
pkg/request/nft_collection.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/service/indexer/indexer.go

**Media**
- Notify user
- Mochi log

feat: send NFT collection integration notification

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot.go
pkg/handler/offchain_tip_bot.go
pkg/response/offchain_tip_bot.go
pkg/routes/v1.go

feat: api get tip bot token

---

Makefile
pkg/entities/offchain_tip_bot_config_notify.go
pkg/entities/offchain_tip_bot_transfer_histories.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/repo/offchain_tip_bot_transfer_histories/mocks/store.go
pkg/repo/offchain_tip_bot_transfer_histories/pg.go
pkg/repo/offchain_tip_bot_transfer_histories/store.go
pkg/routes/v1.go

- New API `/offchain-tip-bot/history` params: `guild_id`, `token`

chore: update tx history

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/community/community.go
pkg/handler/config-channel/config.go
pkg/handler/config-community/config.go
pkg/handler/config-defi/config.go
pkg/handler/config-roles/config.go
pkg/handler/config/config.go
pkg/handler/data/data.go
pkg/handler/defi/defi.go
pkg/handler/nft/nft.go
pkg/handler/tip/tip.go
pkg/handler/user/user.go
pkg/handler/widget/widget.go

-   [x] Update swagger tag by matching route group

chore: update swagger tag by route group

---

pkg/entities/reaction_roles.go

-   [x] Update response messages for reaction roles & default roles

chore: update response for rr & dr features

---

pkg/util/chain.go

-   [x] Fix sol chain id convert

fix: update sol chain id converter

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
pkg/entities/nfts.go
pkg/entities/nfts_test.go
pkg/handler/nft/nft.go
pkg/handler/nft/nft_test.go

-   [x] Add query by collection address instead of checking symbol param is address

fix: get nft query by collection address

---

pkg/util/chain.go

-   [x] Add arbitrum chainId convert

fix: chain convert arbitrum

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml

chore: fix swagger def

---

pkg/config/config.go
pkg/service/abi/abi.go

chore: arbitrum and polygon rpc

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/user/testdata/users/200-user-profiles.json
pkg/model/user_wallet.go
pkg/repo/user_wallet/pg.go

Preload get user wallet

---

pkg/util/chain.go

-   [x] Add sol and polygon chain converter chainid -> chain

fix: update sol and poly chain id converter

---

migrations/schemas/20221228194940-init_dao_voting.sql
pkg/entities/dao_proposal.go
pkg/entities/dao_proposal_vote_option.go
pkg/entities/dao_vote.go
pkg/entities/dao_vote_option.go
pkg/entities/guild_config_dao_proposal.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/handler/handler.go
pkg/model/dao_proposal.go
pkg/model/dao_proposal_vote_option.go
pkg/model/dao_vote.go
pkg/model/dao_vote_option.go
pkg/model/guild_config_dao_proposal.go
pkg/repo/dao_proposal/pg.go
pkg/repo/dao_proposal/store.go
pkg/repo/dao_proposal_vote_option/pg.go
pkg/repo/dao_proposal_vote_option/store.go
pkg/repo/dao_vote/pg.go
pkg/repo/dao_vote/store.go
pkg/repo/dao_vote_option/pg.go
pkg/repo/dao_vote_option/store.go
pkg/repo/guild_config_dao_proposal/pg.go
pkg/repo/guild_config_dao_proposal/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/routes/v1.go

Db: https://dbdiagram.io/d/63abf4417d39e42284e7d8ee
Ref: https://www.notion.so/console-labs/DAO-Voting-Research-and-Data-Model-8f413df1ffa84fb5b0e268d1c507649f

feat: init dao voting

---

migrations/schemas/20221229105300-create_view_dao_proposal.sql

- Add view_dao_proposal to calculate total vote point 
- Add more fields to guild_config_dao_proposal so that admin can config more criteria

chore: update guild config proposal

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/guild_config_dao_proposal.go
pkg/handler/config-channel/config.go
pkg/handler/config-channel/interface.go
pkg/model/guild_config_dao_proposal.go
pkg/repo/guild_config_dao_proposal/pg.go
pkg/repo/guild_config_dao_proposal/store.go
pkg/request/dao_voting.go
pkg/response/dao_voting.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- added `GET` and `DELETE` api for `guild_config_dao_proposal`

chore: dao voting channel api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/dao_vote.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/repo/dao_vote/pg.go
pkg/repo/dao_vote/store.go
pkg/request/dao_voting.go
pkg/routes/v1.go

feat: create dao vote

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/dao_vote.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/model/dao_proposal.go
pkg/repo/dao_proposal/pg.go
pkg/repo/dao_proposal/store.go
pkg/repo/dao_vote/pg.go
pkg/repo/dao_vote/store.go
pkg/response/dao_voting.go
pkg/routes/v1.go

API to get dao votes
For viewing user's all proposals: `/dao-voting/proposals?user-discord-id=<id>`
For viewing proposal's votes: `/dao-voting/proposals/{proposal_id}?user-discord-id=<id>`

chore: view proposals

---

pkg/entities/dao_vote.go
pkg/handler/config-channel/config.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/repo/dao_vote/pg.go
pkg/repo/dao_vote/store.go
pkg/response/config.go
pkg/response/dao_voting.go
pkg/routes/v1.go

-   [x] View proposal vote of user
- Use API **GET** `localhost:8200/dao-voting/proposals/vote`
- Add 2 required query
- `discord-user-id`: Discord user ID (i.e 963123183131709480)
- `proposal-id`: Proposal ID (i.e 1)

feat: dao voting view vote

---

pkg/entities/dao_proposal.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/repo/dao_proposal/pg.go
pkg/repo/dao_proposal/store.go
pkg/repo/dao_proposal_vote_option/pg.go
pkg/repo/dao_proposal_vote_option/store.go
pkg/request/dao_voting.go
pkg/routes/v1.go

-   [x] Add "Delete Proposal API"
- [DELETE] `http://localhost:8200/api/v1/dao-voting/proposals`

feature: add delete proposal api

---

migrations/schemas/20230104155930-add_onchain_transactions.sql
pkg/entities/offchain_tip_bot.go
pkg/entities/onchain_tip_bot.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/model/onchain_tip_bot_transaction.go
pkg/repo/onchain_tip_bot_transaction/pg.go
pkg/repo/onchain_tip_bot_transaction/query.go
pkg/repo/onchain_tip_bot_transaction/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/offchain_tip_bot.go
pkg/request/onchain_tip_bot.go
pkg/response/offchain_tip_bot.go
pkg/response/onchain_tip_bot.go
pkg/routes/v1.go

2 new APIs
```
{
"sender": "760874365037314100",
"recipients": [
"521591222826041344"
],
"guild_id": "878692765683298344",
"channel_id": "923938389764481095",
"amount": 0.1,
"token": "FTM",
"each": false,
"all": false,
"transfer_type": "tip",
"duration": 0,
"full_command": "$tip <@521591222826041344> 0.1 ftm \"hihihi\" --onchain",
"message": "hihihi"
}
```
```
{
"claim_id": 5,
"address": "0xf083A3aeA1f1cDA61813646F2672Ff5Db43Fa8A2$claim",
"user_id": "521591222826041344"
}
```

feat: tip and claim onchain

---

pkg/entities/dao_vote.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/dao-voting/interface.go
pkg/model/dao_vote.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/repo/dao_vote/pg.go
pkg/repo/dao_vote/store.go
pkg/request/dao_voting.go
pkg/response/dao_voting.go
pkg/routes/v1.go

-   [x] Update vote
Use API **PUT** `localhost:8200/dao-voting/proposals/votes/:vote_id`
Add required body request
```json
{
"user_id": "205167514731151360",
"choice": "No" | "Yes" | "Abstain"
}
```

feat: dao voting update vote

---

pkg/entities/dao_proposal.go
pkg/model/dao_proposal_vote_option.go

- change `vote_option_id` to pointer so it nullable

chore: update proposal

---

pkg/entities/onchain_tip_bot.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/repo/onchain_tip_bot_transaction/pg.go
pkg/repo/onchain_tip_bot_transaction/store.go
pkg/response/onchain_tip_bot.go
pkg/routes/v1.go

-   [x] New API to get user's transfers: `[GET] /api/v1/tip/onchain/{user_id}/transfers?status=pending`

fix: tip onchain msg

---

pkg/chain/chain.go
pkg/entities/defi.go
pkg/entities/offchain_tip_bot.go
pkg/entities/onchain_tip_bot.go

fix: onchain balance validation

---

pkg/handler/user/user.go

-   [x] Update to return 404 error when user record is not found

chore: return right status when user record not found

---

pkg/handler/dao-voting/dao-voting.go

- change query id to snake case

chore: update query

---

pkg/config/config.go
pkg/request/nft_collection.go
pkg/service/abi/abi.go
pkg/util/chain.go

chore: support onus collection

---

pkg/entities/guild_config_dao_proposal.go

-   [x] Fix create guild proposal config for admin case

fix: create guild proposal config

---

pkg/entities/guild_config_dao_proposal.go

chore: update proposal config

---

migrations/schemas/20230111142608-alter_dao_proposal_nullable_config.sql

- fix guild config dao proposal delete api

chore: update proposal api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/guild_user.go
pkg/handler/dao-voting/dao-voting.go
pkg/handler/user/interface.go
pkg/handler/user/user.go
pkg/repo/guild_user_activity_log/pg.go
pkg/repo/guild_user_activity_log/store.go
pkg/request/user.go
pkg/routes/v1.go

-   [x] send user xp
-  [x] fix some godoc error

feat: send user xp

---

migrations/schemas/20230112160853-init_token_holder_role.sql
pkg/entities/configs.go
pkg/handler/config-roles/config.go
pkg/handler/config-roles/interface.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/model/guild_config_token_role.go
pkg/repo/guild_config_token_role/pg.go
pkg/repo/guild_config_token_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

-   [x] CRUD token role config
-   Create **POST** `{{baseURL}}/config-roles/token-roles`
```json
{
"guild_id": "1003627546014916688",
"role_id": "1016702420237176903",
"address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
"chain": "eth",
"amount": 300.5
}
```
- Get list role configs of guild **GET** `{{baseURL}}/config-roles/token-roles/{guild_id}`
- Update **PUT** `{{baseURL}}/config-roles/token-roles/{id}`
```json
{
"role_id": "1016702420237176902",
"address": "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE",
"chain": "eth",
"amount": 200
}
```
- Delete **DELETE** `{{baseURL}}/config-roles/token-roles/{id}`

feat: token role config

---

cmd/update-user-token-balances/main.go
cmd/update-user-token-roles/main.go
migrations/schemas/20230113105533-create_user_token_balances_table.sql
pkg/entities/configs.go
pkg/entities/tokens.go
pkg/job/update_user_token_balance.go
pkg/job/update_user_token_roles.go
pkg/model/guild_config_token_role.go
pkg/model/user_token_balance.go
pkg/repo/guild_config_token_role/pg.go
pkg/repo/guild_config_token_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_token_balance/pg.go
pkg/repo/user_token_balance/store.go

-   [x] Job update user token balance
-   [x] Job update user token role
-   Update user token balance: `go run ./cmd/update-user-token-balances/main.go`
-   Update user token role: `go run ./cmd/update-user-token-roles/main.go`

feat: job update discord token role

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
go.sum

-   [x] gen swagger
-   [x] Update notify lib to 0.9.3 to fix deprecated warning -> gen swagger fail

chore: gen swagger

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
go.sum

Reverts consolelabs/mochi-api#640

Revert "chore: gen swagger"

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230116104259-guild_config_levelup_message.sql
pkg/entities/guild_config_levelup_message.go
pkg/handler/community/community.go
pkg/handler/community/interface.go
pkg/model/guild_config_levelup_message.go
pkg/repo/guild_config_levelup_message/pg.go
pkg/repo/guild_config_levelup_message/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

feat: level up msg

---

pkg/entities/guild_config_levelup_message.go

- levelup api: `data: null` for empty record

chore: fix levelup

---

pkg/entities/onchain_tip_bot.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/repo/onchain_tip_bot_transaction/pg.go
pkg/repo/onchain_tip_bot_transaction/query.go
pkg/routes/v1.go

feat: onchain balance

---

pkg/entities/user.go
pkg/repo/guild_config_sales_tracker/mocks/store.go
pkg/repo/guild_user_activity_log/mocks/store.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

- update level up message to use from config
default message, send to chat channel
custom message with no image
custom message with image send to custom channel

chore: update level message

---

pkg/entities/user.go
pkg/service/discord/discord.go

-  add log to user activity handler

chore: log

---

migrations/schemas/20230118100822-envelop_count_streak.sql
pkg/entities/envelop.go
pkg/handler/user/interface.go
pkg/handler/user/user.go
pkg/model/envelop.go
pkg/repo/envelop/pg.go
pkg/repo/envelop/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/envelop.go
pkg/response/user.go
pkg/routes/v1.go

-   [x] create envelop for user
-   [x] sql view count user envelop: `user_envelops`
-   [x] get user envelop streak
- Create envelop for user: **POST** `{{baseURL}}/users/envelop`
JSON Body:
```json
{
"user_id": "205167514731151360",
"command": "$tr"
}
```
- Get user envelop streak: **GET** `{{baseURL}}/users/:id/envelop-streak`
- Create envelop
- Get user envelop streak

feat: envelop count streak

---

pkg/entities/user.go
pkg/entities/user_test.go
pkg/handler/user/testdata/users/200-top-users.json
pkg/response/user.go

chore: update top

---

pkg/entities/dao_proposal.go

- fix error user cannot create proposal with admin perm

chore: fix daovote

---

cmd/update-user-xp-roles/main.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230130141444-init_xp_role.sql
pkg/entities/configs.go
pkg/handler/config-roles/config.go
pkg/handler/config-roles/interface.go
pkg/job/update_user_xp_roles.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/model/guild_config_xp_role.go
pkg/repo/guild_config_xp_role/pg.go
pkg/repo/guild_config_xp_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

-   [x] API set, list, remove xp role config
-   [x] Job update discord role by xp role config
- Set: `POST {{baseURL}}/config-roles/xp-roles`
Example payload
```json
{
"guild_id": "1003627546014916688",
"role_id": "1011978481661386793",
"xp": 20
}
```
- List:  `GET {{baseURL}}/config-roles/xp-roles?guild_id={guild_id}`
- Remove: `{{baseURL}}/config-roles/xp-roles/{id}`

feat: xp role

---

migrations/seed/dao_vote_option.sql
pkg/entities/dao_proposal.go

chore: update daovote

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230201203605-create_nft_soulbound.sql
pkg/entities/nfts.go
pkg/handler/nft/interface.go
pkg/handler/nft/nft.go
pkg/model/nft_soulbound.go
pkg/repo/nft_soulbound/pg.go
pkg/repo/nft_soulbound/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/nft.go
pkg/routes/v1.go
pkg/service/indexer/indexer.go
pkg/service/indexer/mocks/service.go
pkg/service/indexer/service.go

feat: nft soulbound

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/guild_config_dao_proposal.go
pkg/response/dao_voting.go

-add `chain` to guild config daovote response

chore: update dv

---

migrations/schemas/20230201175610-sale_bot_configs.sql
pkg/entities/quest.go
pkg/entities/sale_twitter_bot.go
pkg/handler/config-twitter-sales/config.go
pkg/handler/config-twitter-sales/interface.go
pkg/handler/handler.go
pkg/model/sale_bot_marketplace.go
pkg/model/sale_bot_twitter_config.go
pkg/model/twitter_post_streak.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/sale_bot_marketplace/pg.go
pkg/repo/sale_bot_marketplace/store.go
pkg/repo/sale_bot_twitter_config/pg.go
pkg/repo/sale_bot_twitter_config/query.go
pkg/repo/sale_bot_twitter_config/store.go
pkg/request/twitter_sale_config.go
pkg/response/twitter_sale_config.go
pkg/routes/v1.go

new APIs for twitter sale bot configurations

feat: twitter sale bot

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
go.sum
migrations/schemas/20230204093757-guild_config_dao_tracker.sql
pkg/entities/configs.go
pkg/entities/webhook.go
pkg/handler/config-channel/config.go
pkg/handler/config-channel/interface.go
pkg/handler/webhook/interface.go
pkg/handler/webhook/webhook.go
pkg/model/guild_config_dao_tracker.go
pkg/repo/guild_config_dao_tracker/pg.go
pkg/repo/guild_config_dao_tracker/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/dao_voting.go
pkg/request/snapshot.go
pkg/response/config.go
pkg/response/snapshot.go
pkg/routes/v1.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/service/service.go
pkg/service/snapshot/service.go
pkg/service/snapshot/snapshot.go
pkg/util/util.go

- CRUD dao proposal notify channel
- Webhook for Snapshot proposal

feat: snapshot proposal

---

pkg/service/coingecko/coingecko.go

-   [x] skip call coingecko when icy only

chore: skip call coingecko when icy only

---

pkg/handler/tip/tip.go
pkg/repo/offchain_tip_bot_chain/pg.go
pkg/repo/offchain_tip_bot_chain/store.go

Fix error happens when both conditions matched:
1. no more available contracts for that token
2. one contract of that token already assigned to that user and hasn't been expired

fix: assign contract error

---

Makefile
migrations/schemas/20230207234146-user_wallet_watchlist_items.sql
pkg/entities/wallet.go
pkg/handler/handler.go
pkg/handler/wallet/interface.go
pkg/handler/wallet/wallet.go
pkg/job/watch_evm_deposits.go
pkg/model/user_wallet_watchlist_item.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_wallet_watchlist_item/pg.go
pkg/repo/user_wallet_watchlist_item/query.go
pkg/repo/user_wallet_watchlist_item/store.go
pkg/request/wallet.go
pkg/response/wallet.go
pkg/routes/v1.go
pkg/service/covalent/covalent.go
pkg/service/covalent/mocks/service.go
pkg/service/covalent/model.go
pkg/service/covalent/service.go

New APIs for wallet tracking
-   [x] `[GET] /api/v1/users/{id}/wallets`: list tracking wallets
-   [x] `[GET] /api/v1/users/{id}/wallets/{address}`: find wallet
-   [x] `[GET] /api/v1/users/{id}/wallets/{address}/assets`: list wallet assets
-   [x] `[GET] /api/v1/users/{id}/wallets/address}/txns`: list wallet transactions
-   [x] `[POST] /api/v1/users/{id}/wallets/track`: track new wallet
-   [x] `[POST] /api/v1/users/{id}/wallets/untrack`: untrack a wallet

feat: wallet tracking

---

cmd/update-user-mix-roles/main.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230206155703-init_mix_role.sql
pkg/entities/guild_config_mix_role.go
pkg/handler/config-roles/config.go
pkg/handler/config-roles/interface.go
pkg/job/update_user_mix_roles.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/model/guild_config_mix_role.go
pkg/repo/guild_config_mix_role/pg.go
pkg/repo/guild_config_mix_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/token/mocks/store.go
pkg/repo/token/pg.go
pkg/repo/token/store.go
pkg/request/guild_config_mix_role.go
pkg/response/config.go
pkg/routes/v1.go

Add API and jobs for feature mix role
-   [x] `[POST] {{baseURL}}/config-roles/mix-roles`
-   [x] `[GET] {{baseURL}}/config-roles/mix-roles?guild_id={guild_id}`
-   [x] `[DELETE] {{baseURL}}/config-roles/mix-roles/{id}`
-   [x] Job `update-user-mix-roles`

feat: mix role

---

pkg/entities/wallet.go

-   [x] Increase retry times to 5 for failed covalent API requests

fix: covalent retry

---

pkg/entities/quest.go
pkg/entities/wallet.go
pkg/response/wallet.go
pkg/service/covalent/model.go
pkg/util/util.go

fix: wallet assets and txns logic

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/configs.go
pkg/entities/tokens.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/handler/wallet/wallet.go
pkg/response/defi.go
pkg/routes/v1.go

-   Would use this API for getting token detail in mix role feature
-   [x] `[GET] {{baseURL}}/api/v1/defi/token?address={token_address}&chain={chain}`

feat: mix role get token detail

---

migrations/schemas/20230215164431-add_wallet_type.sql
pkg/entities/wallet.go
pkg/model/user_wallet_watchlist_item.go
pkg/request/wallet.go
pkg/response/wallet.go
pkg/routes/v1.go
pkg/service/service.go
pkg/service/solscan/model.go
pkg/service/solscan/service.go
pkg/service/solscan/solscan.go

feat: wallet - support solana

---

cmd/commonwealth_proposal_check/main.go
migrations/schemas/20230215125246-commonwealth_lastest_data.sql
migrations/schemas/20230215161550-alter_dao_tracker.sql
pkg/entities/configs.go
pkg/entities/dao_proposal.go
pkg/entities/webhook.go
pkg/job/commonwealth_proposal_check.go
pkg/model/commonwealth_latest_data.go
pkg/model/guild_config_dao_tracker.go
pkg/repo/commonwealth_latest_data/pg.go
pkg/repo/commonwealth_latest_data/store.go
pkg/repo/guild_config_dao_tracker/pg.go
pkg/repo/guild_config_dao_tracker/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/snapshot.go
pkg/service/commonwealth/commonwealth.go
pkg/service/commonwealth/service.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go
pkg/service/service.go
pkg/util/util.go

-  add [Commonwealth](https://commonwealth.im/docs/#/default/get_threads) api and cronjob to call them
- send discussion to config when detect new discussion
Flow: user add config -> map all unique communities -> call commonwealth api to query communities -> check if response data is newer than db -> send notification to discord

feat: commonwealth proposal

---

pkg/handler/config-community/config.go
pkg/handler/config-community/config_test.go
pkg/handler/config-community/testdata/404_record_not_found.json

When no twitter config found
- Now: returned 200
- Fixed: return 404

fix: twitter config error response

---

pkg/entities/offchain_tip_bot.go

chore: update emoji

---

pkg/entities/wallet.go
pkg/job/fetch_discord_users.go
pkg/model/user_wallet_watchlist_item.go

-   [x] Ignore if failed to fetch wallet's net worth

fix: view wallet

---

pkg/entities/wallet.go
pkg/service/covalent/covalent.go
pkg/service/covalent/mocks/service.go
pkg/service/covalent/model.go
pkg/service/covalent/service.go

-   [x] Fix unstable wallet APIs

fix: unstable wallet API

---

pkg/handler/tip/tip.go

-   [x] Update contract assignments expiration time: 3 days -> 3 hours

fix: contract assignment - update expiration

---

cmd/watch-solana-deposits/main.go
migrations/schemas/20230221173403-add_sol_contract_pk.sql
pkg/chain/solana.go
pkg/config/config.go
pkg/entities/offchain_tip_bot.go
pkg/model/offchain_tip_bot_contract.go
pkg/util/encryption.go

-   [x] deposit: sweep solana (transfer all from contract to centralized wallet) when receives new deposit

feat: deposit - solana sweep tokens

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/dao_proposal.go
pkg/repo/dao_proposal/pg.go
pkg/repo/dao_proposal/store.go
pkg/repo/guild_config_dao_tracker/pg.go
pkg/repo/guild_config_dao_tracker/store.go
pkg/response/dao_proposal.go

-   [x] Fix total in pagination for proposal internal

fix: proposal internal pagination

---

pkg/service/solscan/solscan.go

-   [x] Add API key for solscan requests

fix: solscan requests - add token

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi/defi_test.go
pkg/handler/defi/testdata/user_watchlist/get-200-ok-custom.json
pkg/handler/defi/testdata/user_watchlist/get-200-ok-default.json
pkg/response/defi.go

feat: wl paging

---

pkg/entities/nfts.go

chore: fix nft wl

---

migrations/schemas/20230227133457-remove_deposit_log_user_reference.sql
pkg/entities/offchain_tip_bot.go
pkg/job/watch_evm_deposits.go

Solution: should iterate through all event logs instead of checking only first one

fix: evm deposit patch

---

migrations/schemas/20230227222201-remove_user_discord_wallet.sql
pkg/entities/defi.go
pkg/entities/user.go
pkg/entities/verification.go
pkg/model/user.go
pkg/repo/users/pg.go
pkg/repo/users/store.go
pkg/response/user.go

-   [x] Since we no longer user in-discord wallet -> remove them

fix: remove user discord wallet

---

pkg/entities/user.go
pkg/entities/verification.go
pkg/handler/webhook/webhook.go
pkg/job/fetch_discord_users.go
pkg/repo/guild_users/pg.go
pkg/repo/guild_users/store.go
pkg/repo/users/pg.go
pkg/repo/users/store.go

refactor: fetch discord users

---

migrations/schemas/20230228162235-update_offchain_contract.sql
pkg/chain/chain.go
pkg/entities/offchain_tip_bot.go
pkg/entities/wallet.go

Transfer transaction: await for tx status

fix: withdraw - await minted

---

pkg/chain/chain.go

-   [x] temp workaround: set gas limit to 1m for fbomb case

fix: fbomb gas issue

---

pkg/entities/offchain_tip_bot.go
pkg/job/watch_evm_deposits.go
pkg/model/offchain_tip_bot_assign_contract.go
pkg/model/offchain_tip_bot_assign_contract_log.go
pkg/model/offchain_tip_bot_contract.go
pkg/repo/offchain_tip_bot_contract/pg.go
pkg/repo/offchain_tip_bot_contract/query.go
pkg/repo/offchain_tip_bot_contract/store.go
pkg/repo/offchain_tip_bot_deposit_log/pg.go
pkg/repo/offchain_tip_bot_deposit_log/store.go

New flow
1. fetch contract's txns every 5/10m
2. check whether tx was handled by job
3. validate whether each tx is deposit tx
4. if yes then handle (store tx/logs to DB + update user balance + notify through discord)

refactor: deposit scanner

---

pkg/entities/defi.go
pkg/request/defi.go

chore: watchlist query

---

migrations/schemas/20230302151407-set_unique_idx_token_price_alert.sql
pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/response/binance.go
pkg/routes/v1.go
pkg/service/binance/binance.go
pkg/service/binance/service.go

chore: add get binance coin price handler & add unique index

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230302194416-proposal-discussion-commonwealth.sql
pkg/entities/configs.go
pkg/entities/proposal_discussion.go
pkg/handler/config-channel/config.go
pkg/handler/config-channel/interface.go
pkg/handler/wallet/wallet.go
pkg/job/commonwealth_proposal_check.go
pkg/model/commonwealth_latest_data.go
pkg/repo/commonwealth_discussion_subscriptions/pg.go
pkg/repo/commonwealth_discussion_subscriptions/store.go
pkg/repo/offchain_tip_bot_contract/mocks/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/commonwealth.go
pkg/request/dao_voting.go
pkg/response/dao_proposal.go
pkg/response/snapshot.go
pkg/routes/v1.go
pkg/service/commonwealth/commonwealth.go
pkg/service/commonwealth/service.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

-   [x] Update Discord Commonwealth dao tracking log message UI
-   [x] Add API for create cw discussion subscription
ref: [ticket](https://www.notion.so/console-labs/2b9be3fffef74705830ad77058e35c95?v=820e468ba3ab4bb08201c8fa5c545674&p=89df186d5b0641dcb8826f62f077fd41&pm=s)

feat: proposal discussion

---

pkg/job/commonwealth_proposal_check.go
pkg/service/discord/discord.go

-   [x] Update commonwealth icon url in footer
-   [x] Update discussion link
-   [x] Update component custom_id
-   [x] Fix update commonwealth_latest_data logic

fix: proposal discussion

---

pkg/entities/offchain_tip_bot.go

chore: update deposit ui

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230306101748-user_submitted_ads.sql
pkg/config/config.go
pkg/entities/user_submitted_ad.go
pkg/handler/community/community.go
pkg/handler/community/interface.go
pkg/model/user_submitted_ad.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_submitted_ad/pg.go
pkg/repo/user_submitted_ad/store.go
pkg/request/community.go
pkg/response/user_submitted_ad.go
pkg/routes/v1.go

- API for dynamic ad submission
- Flow: -> user uses command -> BE create channel and store data -> BE post notification to channel -> FE handle button interaction to update ad status
- Approve button id :`ad-approve-{ad_id}`, reject: `ad-reject-{ad_id}`
- **GET**: `/community/advertise/:id`, to get random ad: `/community/advertise/random`
POST body

feat: dynamic ads

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230307114504-alter-user-submitted-ad.sql
pkg/entities/user_submitted_ad.go
pkg/model/user_submitted_ad.go
pkg/request/community.go

- add field `is_podtown_ad` to table `user_submitted_ads`

chore: update dynamic ad

---

pkg/entities/defi.go
pkg/entities/offchain_tip_bot.go
pkg/service/discord/discord.go

-   [x] Send tip-bot activities to server's  log channel

feat: tip bot activity notification

---

pkg/entities/defi.go

-   [x] Hard-coded for `skull` alias

chore: hardcoded recommendation list for skullswap-exchange

---

pkg/entities/nfts.go

fix: nft suggestions

---

pkg/entities/verification.go

- fix `verify remove` case where user delete verify channel

chore: fix verify remove

---

pkg/entities/guild_config_dao_proposal.go

-   [x] fix guideline proposal msg

chore: fix guide msg

---

.env.sample
go.mod
go.sum
pkg/chain/solana.go
pkg/config/config.go
pkg/entities/dao_proposal.go
pkg/entities/guild_config_dao_proposal.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/model.go
pkg/service/mochiprofile/service.go
pkg/service/service.go

-   [x] Support Solana for DAO proposal create / vote
- Create guild DAO config with Solana token
**NOTE**
- Need to add new variable `MOCHI_PROFILE_SERVER_HOST` to .env
https://share.cleanshot.com/K5HHJJY8

feat: support solana for dao proposal

---

pkg/entities/dao_proposal.go

-   [x] Fix the required amount dao voting token

fix: required amount dao voting

---

pkg/entities/dao_proposal.go

-   [x] Fix logic to check requirement for dao voting

fix: dao voting requirement logic

---

pkg/service/mochiprofile/model.go

-   [x] Udpate mochi profile response

fix: change response mochi profile

---

pkg/entities/user_token_support_request.go
pkg/repo/user_token_support_request/pg.go
pkg/repo/user_token_support_request/store.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

-   [x] Notify the user when token support approved/rejected

feat: update status token request

---

migrations/schemas/20230327214922-alter_user_token_support_request.sql
pkg/entities/user_token_support_request.go
pkg/model/errors/validator.go
pkg/model/user_token_support_request.go
pkg/request/user_token_support_request.go

chore: update token add cmd

---

pkg/repo/guild_user_xp/pg.go

fix: sort top users

---

pkg/entities/defi.go
pkg/entities/tokens.go
pkg/handler/defi/defi.go
pkg/repo/token/mocks/store.go
pkg/repo/token/pg.go
pkg/repo/token/store.go

-   [x] Add pagination for get supported tokens API

chore: add pagination for get supported token api

---

pkg/repo/guild_user_xp/pg.go

-   [x] Using ILIKE for search leaderboard case-insensitive

fix: lb search user case-insensitive

---

pkg/entities/user.go

In this previous version, we sort guild member roles by the ID, but they should be ordered by their position. So this PR is used to fix this.
-   [x] Fix cronjob fetch guild user: Add order roles by position

fix: sort guild member roles by position

---

pkg/repo/token/pg.go

chore: update token list order

---

migrations/schemas/20230403134354-kyberswap_supported_tokens.sql
pkg/entities/swap.go
pkg/handler/swap/swap.go
pkg/model/kyberswap_supported_tokens.go
pkg/repo/kyberswap_supported_tokens/pg.go
pkg/repo/kyberswap_supported_tokens/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/swap.go
pkg/service/kyber/interface.go
pkg/service/kyber/kyber.go
pkg/util/util.go

refactor: fetch token data and query api

---

migrations/schemas/20230404102809-alter_vault_tables.sql
pkg/consts/vault.go
pkg/entities/vault.go
pkg/handler/vault/interface.go
pkg/handler/vault/vault.go
pkg/model/treasurer.go
pkg/model/treasurer_request.go
pkg/model/treasurer_submission.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/treasurer/pg.go
pkg/repo/treasurer/store.go
pkg/repo/treasurer_submission/pg.go
pkg/repo/treasurer_submission/store.go
pkg/request/vault.go
pkg/response/vault.go
pkg/routes/v1.go

https://www.loom.com/share/b55b2dd94ebe4bbbb74185971ddcce8e

feat: flow add treasurer

---

Makefile
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/dao_proposal.go
pkg/entities/verification.go
pkg/handler/verify/interface.go
pkg/handler/verify/verify.go
pkg/request/verification.go
pkg/routes/v1.go
pkg/service/mochiprofile/model.go

-   [x] Add api to trigger assign verified role if user have associated wallet from mochi profile
```sh
curl -X 'POST' \
'http://localhost:8200/api/v1/verify/assign-role' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"guild_id": "1003627546014916688",
"user_discord_id": "205167514731151360"
}'
```

fix: verified role

---

pkg/entities/vault.go
pkg/handler/vault/interface.go
pkg/handler/vault/vault.go
pkg/repo/treasurer/pg.go
pkg/repo/treasurer/store.go
pkg/response/vault.go
pkg/routes/v1.go

- Logic của cái này vẫn đang discuss, nên hầu hết data em đang mock trước

feat: vault detail

---

migrations/schemas/20230406095636-create_vault_transactions.sql
pkg/consts/vault.go
pkg/entities/vault.go
pkg/model/treasurer_request.go
pkg/model/vault_transaction.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/treasurer_request/pg.go
pkg/repo/treasurer_request/store.go
pkg/repo/vault_transaction/pg.go
pkg/repo/vault_transaction/store.go
pkg/response/vault.go
pkg/util/util.go

feat: track vault history

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/swap.go
pkg/response/kyber.go

chore: kyberswap token

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/swap.go
pkg/handler/swap/swap.go
pkg/model/kyberswap.go
pkg/repo/kyberswap_supported_tokens/pg.go
pkg/repo/kyberswap_supported_tokens/store.go
pkg/request/kyberswap.go
pkg/response/kyber.go
pkg/response/swap.go
pkg/service/kyber/interface.go
pkg/service/kyber/kyber.go

- Có nhiều field bên solana không có, em đang trả hết những gì api bên kyber có

feat: kyber swap solana

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230410054010-add-table-user-tags.sql
pkg/entities/user_tag.go
pkg/handler/community/community.go
pkg/handler/community/interface.go
pkg/model/user_tag.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_tag/pg.go
pkg/repo/user_tag/query.go
pkg/repo/user_tag/store.go
pkg/request/community.go
pkg/routes/v1.go

-   [x] Add api get user tag 
-   [x] Add api upsert user tag

feat: add api get user tag

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230410091643-alter-table-user-tags-add-is-active-field.sql
pkg/entities/user_tag.go
pkg/model/user_tag.go
pkg/request/community.go

-   [x] Change field logic in user tag model

chore: add new field on user tag

---

pkg/entities/user.go
pkg/model/guild_user.go

fix: welcome msg

---

pkg/entities/swap.go
pkg/handler/swap/swap.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/model.go
pkg/service/mochipay/service.go
pkg/util/bigint.go

chore: handle insufficient bal swap

---

migrations/schemas/20230414123104-update_offchain_token.sql
pkg/entities/defi_test.go
pkg/entities/user_token_support_request.go
pkg/handler/defi/defi_test.go
pkg/model/user_token_support_request.go
pkg/repo/offchain_tip_bot_tokens/mocks/store.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go
pkg/response/defi.go
pkg/service/abi/mocks/service.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/request.go
pkg/service/mochipay/service.go

Add token request
-   [x] More fields when user request to add new token

feat: token request

---

pkg/entities/offchain_tip_bot.go
pkg/entities/onchain_tip_bot.go
pkg/entities/user_token_support_request.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go
pkg/request/offchain_tip_bot.go
pkg/response/offchain_tip_bot.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/model.go
pkg/service/mochipay/request.go
pkg/service/mochipay/service.go
pkg/util/bigint.go

refactor: offchain transfer

---

pkg/consts/offchain_tip_bot.go
pkg/entities/offchain_tip_bot.go
pkg/repo/offchain_tip_bot_tokens/mocks/store.go
pkg/service/discord/discord.go
pkg/service/discord/mocks/service.go
pkg/service/discord/service.go

-   [x] Resolve [notion ticket](https://www.notion.so/console-labs/Log-Message-268e58f9e3e1418494caed69b8387bc4)

chore: edit notify messages

---

migrations/schemas/20230421100947-create_contrain_gm.sql
pkg/entities/configs.go
pkg/entities/webhook.go
pkg/repo/guild_config_gm_gn/mocks/store.go
pkg/repo/guild_config_gm_gn/pg.go
pkg/repo/guild_config_gm_gn/store.go

-   [x] Upsert gm channel config

fix: gm guild config upsert

---

pkg/entities/user_token_support_request.go
pkg/repo/offchain_tip_bot_tokens/pg.go
pkg/repo/offchain_tip_bot_tokens/store.go

-   [x] when approve user's new token request, still need to add it to table offchain_tip_bot_tokens since it's a moniker's dependect and we have not migrated moniker to mochi_pay

fix: add token request

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230420145727-create-table-guild-config-tip-range.sql
pkg/entities/configs.go
pkg/entities/offchain_tip_bot.go
pkg/handler/config-defi/config.go
pkg/handler/config-defi/interface.go
pkg/model/guild_config_tip_range.go
pkg/repo/guild_config_tip_range/pg.go
pkg/repo/guild_config_tip_range/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/config.go
pkg/response/config.go
pkg/routes/v1.go

-   [x] Add upsert tip range config api
-   [x] validate price min/max when already config and have coingecko price usd

chore: add new tiprange api and validate when transfer token

---

pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/routes/v1.go

feat: gainer loser for all token

---

pkg/service/discord/discord.go

fix: outdated approve emoji

---

migrations/schemas/20230508145247-alter_vault_add_walet_number.sql
pkg/config/config.go
pkg/entities/entity.go
pkg/entities/vault.go
pkg/model/vault.go
pkg/repo/vault/pg.go
pkg/repo/vault/store.go
pkg/request/vault.go
pkg/vaultwallet/vaultwallet.go

- Gen wallet when desig mode = false -> default is false
- Vault info show real wallet

chore: vault use real wallet address

---

pkg/entities/offchain_tip_bot.go
pkg/entities/onchain_tip_bot.go
pkg/entities/user_token_support_request.go
pkg/handler/tip/interface.go
pkg/handler/tip/tip.go
pkg/routes/v1.go

-   [x] Remove transfer all logic

fix: remove transfer all logic

---

pkg/entities/vault.go
pkg/request/vault.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/model.go
pkg/service/mochipay/service.go
pkg/util/bigint.go
pkg/vaultwallet/vaultwallet.go

https://www.loom.com/share/4d649ae1b2624d06bc9009bdf745637b

feat: treasurer transfer send money

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/defi/defi.go

-   [x] fix swagger defi relative routes

chore: fix swagger defi relative routes

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/api_key.go
pkg/handler/api-key/api_key.go
pkg/handler/api-key/interface.go
pkg/handler/handler.go
pkg/response/api_key.go
pkg/routes/v1.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/model.go
pkg/service/mochiprofile/service.go

feat: add api key routes

---

pkg/entities/defi.go
pkg/response/defi.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

-   [x] Update `/defi/market-chart` endpoint: support btc dominance chart

feat: btc dominance chart data

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/api_key.go
pkg/handler/api-key/api_key.go
pkg/handler/api-key/interface.go
pkg/middleware/auth.go
pkg/routes/v1.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/service.go

-   [x] Enhance flow generate api key with profileAccessToken

chore: enhance api key flow

---

pkg/entities/vault.go
pkg/handler/vault/interface.go
pkg/handler/vault/vault.go
pkg/routes/v1.go
pkg/util/address.go

behaviour of transfer by address the same transfer to user

feat: transfer vault by address

---

pkg/handler/vault/vault.go

-   [x] add vault not found response

chore: add vault not found response

---

pkg/handler/vault/vault.go

-   [x] edit vault not found response

chore: edit vault not found response

---

pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/coingecko_test.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

feat: add brc20 coins

---

pkg/entities/defi.go
pkg/service/coingecko/coingecko.go

fix: fix brc20 data

---

pkg/service/coingecko/coingecko.go

fix: brc20 token query

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/defi/defi.go

chore: update public swagger

---

pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi/defi.go
pkg/handler/defi/testdata/get_coin/200-success-eth.json
pkg/request/defi.go
pkg/response/defi.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

feat: enhance dominance chart

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230515221742-add-table-guild-config-admin-roles.sql
pkg/entities/guild_config_admin_role.go
pkg/handler/config-roles/config.go
pkg/handler/config-roles/interface.go
pkg/model/guild_config_admin_role.go
pkg/repo/guild_config_admin_role/pg.go
pkg/repo/guild_config_admin_role/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/guild_config_admin_role.go
pkg/response/config.go
pkg/routes/v1.go

-   [x] Add apis set admin roles

chore: add set admin role config

---

pkg/entities/user_token_support_request.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/response/defi.go
pkg/service/covalent/covalent.go

Add token request
-   [x] Update errors status + message

fix: token add request datasource

---

migrations/schemas/20230518164430-remove_guild_activities_fkey.sql
pkg/entities/guild.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/handler/webhook/webhook.go
pkg/handler/webhook/webhook_test.go
pkg/repo/discord_guilds/pg.go
pkg/repo/guild_config_activity/pg.go
pkg/request/guild.go

-   [x] Fix webhook 500 error: because some guilds were not created when Mochi Bot joined (maybe server was down at that time)

fix: discord webhook error

---

pkg/entities/vault.go
pkg/response/vault.go

Khôi tạo request thêm Huy vô vault (66%)
+ Lúc này chỉ có Khôi là treasurer -> số approve là 1/1 = 100 % -> add luôn 
+ Khôi tiếp tục tạo request thêm Minh vô -> lúc này số approve chỉ là 1/2 (do Huy chưa approve) -> đợi Huy bấm nút -> ... -> flow như cũ

chore: enhance vault logic

---

migrations/schemas/20230522132012-alter_vault_add_solana_wallet.sql
pkg/config/config.go
pkg/entities/vault.go
pkg/model/vault.go
pkg/response/vault.go
pkg/vaultwallet/vaultwallet.go

https://solscan.io/tx/3DGFTgx4RHSTkQALLan9hbvKJtJzCtzDfwFqPATjp6FAuQMLAU4Rt7ggoaTQvQsTZcnWxRtdz9MSj5Af5aCcJGuo

feat: vault transfer solana

---

pkg/entities/nfts.go
pkg/handler/nft/nft.go

chore: check nft not found

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/vault.go
pkg/handler/vault/interface.go
pkg/handler/vault/vault.go
pkg/model/treasurer.go
pkg/model/vault.go
pkg/repo/vault/pg.go
pkg/repo/vault/query.go
pkg/repo/vault/store.go
pkg/request/vault.go
pkg/response/vault.go
pkg/routes/v1.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/model.go
pkg/service/mochiprofile/service.go

-   [x] Update list vaults endpoint: `[GET] /api/v1/vault`

feat: list vaults endpoint

---

pkg/handler/vault/validation.go
pkg/handler/vault/vault.go

chore: limit vault name 24 char

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/vault.go
pkg/model/vault.go

feat: total amount vault

---

pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/handler/defi/testdata/get_coin/200-success-eth.json
pkg/response/defi.go

feat: ticker add categories

---

pkg/entities/vault.go
pkg/entities/wallet.go
pkg/handler/wallet/wallet.go
pkg/repo/wallet_snapshot/pg.go
pkg/response/wallet.go

feat: wallet pnl

---

pkg/entities/wallet.go

-   [x] Wallet txn: return empty array instead of null

fix: filter out dusty wallet balances

---

pkg/entities/vault.go
pkg/response/vault.go

chore: update logic bal vault detail

---

pkg/config/config.go
pkg/entities/wallet.go
pkg/response/sui.go
pkg/service/service.go
pkg/service/sui/service.go
pkg/service/sui/sui.go
pkg/util/bigint.go

-   [x] get sui wallet asset 
- api list wallet assets

feat: get sui wallet assets

---

pkg/entities/wallet.go
pkg/request/wallet.go

-   [x] Support ronin for wallets API

feat: wallet - support ronin

---

pkg/entities/wallet.go
pkg/response/sui.go
pkg/service/sui/service.go
pkg/service/sui/sui.go

feat: get sui wallet txn

---

pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/entities/tokens_test.go
pkg/handler/config-defi/config_test.go
pkg/handler/defi/defi_test.go
pkg/handler/defi/testdata/search_coin/200-ok-multiple.json
pkg/handler/defi/testdata/search_coin/200-ok-single.json
pkg/handler/defi/testdata/user_watchlist/post-200-ok-suggest.json
pkg/model/coingecko_supported_tokens.go

-   [x] Add `current_price` to search coins API

fix: add current price to coin suggestions

---

.env.sample
pkg/config/config.go
pkg/entities/binance_data.go
pkg/handler/api-key/api_key.go
pkg/handler/api-key/interface.go
pkg/model/binance_data.go
pkg/request/binance_data.go
pkg/routes/v1.go

-   [x] produce binance data to kafka
- api
- kafka

feat: add api integrate binance data

---

pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi/defi_test.go
pkg/handler/defi/testdata/user_watchlist/200-add-single.json
pkg/handler/defi/testdata/user_watchlist/post-200-ok-suggest.json
pkg/response/defi.go

-   [x] Update add to watchlist API: add coin info to response

fix: add wl - respond coin info

---

pkg/entities/swap.go
pkg/handler/swap/swap.go

- Instead crash bot now return message

fix: handle case kyber no data

---

pkg/entities/defi.go
pkg/entities/wallet.go

-   [x] add usd balance for sui wallet

chore: add usd balance for sui wallet

---

pkg/entities/defi.go
pkg/entities/user_token_support_request.go
pkg/handler/defi/testdata/get_coin/200-success-eth.json
pkg/response/defi.go
pkg/service/coingecko/coingecko.go
pkg/service/coingecko/mocks/service.go
pkg/service/coingecko/service.go

-   [x] Update get coin api: `[GET] /api/v1/defi/coins/{id}` -> return chain info object

fix: chain abbreviation

---

pkg/entities/wallet.go

fix: wallet txns

---

pkg/entities/binance_data.go
pkg/entities/vault.go
pkg/request/vault.go

-   [x] change kafka vault message

chore: change kafka vault message

---

pkg/entities/wallet.go
pkg/response/wallet.go
pkg/service/sui/sui.go

-   [x] Update wallet assets API: add chain symbol to response

fix: wallet response with chain symbol

---

pkg/entities/defi.go

-   [x] Fix watchlist API: 24h price change % always = 0

fix: wl - 24h price change percentage

---

migrations/schemas/20230608125530-create-emojis.sql
pkg/entities/emojis.go
pkg/handler/emojis/emojis.go
pkg/handler/emojis/interface.go
pkg/handler/handler.go
pkg/model/emojis.go
pkg/repo/emojis/pg.go
pkg/repo/emojis/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/emojis.go
pkg/routes/v1.go

-   [x] add emojis api
- Get `api/v1/emojis?codes=eth,ftm`

feat: add emoji api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230608171958-add-table-earn-and-user-earn.sql
pkg/entities/earn.go
pkg/handler/earn/earn.go
pkg/handler/earn/interface.go
pkg/handler/handler.go
pkg/handler/pk-pass/pk_pass.go
pkg/model/earn.go
pkg/model/user_earn.go
pkg/repo/earn_info/pg.go
pkg/repo/earn_info/query.go
pkg/repo/earn_info/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/user_earn/pg.go
pkg/repo/user_earn/query.go
pkg/repo/user_earn/store.go
pkg/request/earn_info.go
pkg/response/earn.go
pkg/routes/v1.go

chore: add earn routes

---

pkg/consts/platform.go
pkg/entities/wallet.go
pkg/handler/dex/dex.go
pkg/handler/dex/interface.go
pkg/handler/handler.go
pkg/handler/wallet/interface.go
pkg/handler/wallet/wallet.go
pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/request/binance_data.go
pkg/response/wallet.go
pkg/routes/v1.go
pkg/service/mochiprofile/model.go

feat: api get binance asset

---

Dockerfile

fix: fix missing images

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/earn.go
pkg/handler/earn/earn.go
pkg/model/earn.go
pkg/repo/earn_info/pg.go
pkg/repo/earn_info/query.go
pkg/repo/user_earn/pg.go
pkg/repo/user_earn/query.go
pkg/request/earn_info.go

-   [x] Add filter status earn api

chore: add earn filter status

---

migrations/schemas/20230612135210-create_table_header_content.sql
pkg/entities/content.go
pkg/handler/content/content.go
pkg/handler/content/interface.go
pkg/handler/handler.go
pkg/model/content.go
pkg/repo/content/pg.go
pkg/repo/content/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/response/content.go
pkg/routes/v1.go

- data in db
- api return data

feat: create content for reminder

---

pkg/entities/defi.go
pkg/entities/defi_test.go

-   [x] Get token usd price for search coins

fix: search coins

---

pkg/consts/address.go
pkg/entities/wallet.go
pkg/service/birdeye/birdeye.go
pkg/service/birdeye/model.go
pkg/service/birdeye/service.go
pkg/service/service.go

fix: get sol price

---

pkg/entities/swap.go
pkg/entities/swap_util.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/request.go
pkg/service/mochipay/service.go
pkg/util/chain.go

refactor: submit swap

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230615161329-alter-table-airdrop-campaigns.sql
pkg/handler/airdrop-campaign/airdrop_campaign.go
pkg/model/earn.go
pkg/repo/airdrop_campaign/pg.go
pkg/request/airdrop_campaign.go

-   [x]alter table airdrop campaign

chore: alter airdrop campaign

---

pkg/entities/verification.go
pkg/entities/wallet.go
pkg/model/user_wallet_watchlist_item.go
pkg/request/wallet.go
pkg/service/covalent/covalent.go

-   [x] Change chain type from `ethereum` to `evm`
-   [x] Avoid covalent timeout temporarily

fix: change chain type and avoid covalent timout temporarily

---

pkg/entities/nfts.go
pkg/response/solscan.go

-   [x] add sol nft collection

fix: add sol nft collection

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/airdrop_campaign.go
pkg/handler/airdrop-campaign/airdrop_campaign.go
pkg/handler/airdrop-campaign/interface.go
pkg/request/airdrop_campaign.go
pkg/response/airdrop_campaign.go
pkg/routes/v1.go

-   [x] Fix standard response structure
-   [x] Add new api get airdrop campagin by id

chore: fix standard response

---

pkg/entities/wallet.go
pkg/service/covalent/covalent.go

feat: wallet sp arbitrum

---

pkg/entities/emojis.go
pkg/model/emojis.go

-   [x] format emoji data response

chore: refactor emoji api

---

pkg/entities/swap.go
pkg/service/swap/provider/kyber.go

fix: swap usdt usdc

---

pkg/entities/defi_test.go
pkg/entities/entity.go
pkg/entities/wallet.go
pkg/handler/cache/cache_test.go
pkg/handler/community/community_test.go
pkg/handler/config-channel/config_test.go
pkg/handler/config-community/config_test.go
pkg/handler/config-defi/config_test.go
pkg/handler/config-roles/config_test.go
pkg/handler/config/config_test.go
pkg/handler/data/data_test.go
pkg/handler/defi/defi_test.go
pkg/handler/defi/testdata/get_coin/200-success-eth.json
pkg/handler/defi/testdata/search_coin/200-ok-multiple.json
pkg/handler/defi/testdata/search_coin/200-ok-single.json
pkg/handler/defi/testdata/user_watchlist/post-200-ok-suggest.json
pkg/handler/nft/nft_test.go
pkg/handler/user/user_test.go
pkg/handler/webhook/webhook_test.go
pkg/service/skymavis/skymavis.go

-   [x] Do not declare error for case status is not 200 when calling API skymavis -> Let both error and result is null -> Panic
-   [x] Missing whitelisting chain id when calculating eth wallet networth -> return wrong total value

chore: fix minor bug in the tracking apis

---

pkg/entities/wallet.go
pkg/handler/wallet/wallet.go
pkg/response/wallet.go
pkg/service/skymavis/service.go
pkg/service/skymavis/skymavis.go

-   [x] List wallet assets API: return nft data (only AXIE supported for now)

feat: wallet - axie nft data

---

pkg/entities/wallet.go
pkg/response/wallet.go
pkg/service/skymavis/query.go
pkg/service/skymavis/service.go
pkg/service/skymavis/skymavis.go

-   [x] Query axie NFT collections data: land, items, accessories and axies

refactor: wallet axie nft

---

.env.sample
pkg/config/config.go
pkg/entities/wallet.go
pkg/service/krystal/krystal.go
pkg/service/krystal/response.go
pkg/service/krystal/service.go
pkg/service/service.go

-   [x] Change API get EVM assets from Colavent to Krystal

chore: call api krystal for evm data

---

pkg/entities/entity.go
pkg/entities/wallet.go
pkg/job/watch_dm_notify_price_alert.go
pkg/service/krystal/krystal.go
pkg/service/krystal/service.go
pkg/service/service.go

-   [x] Add cache for krystal service

chore: add cache krystal service

---

pkg/entities/entity.go
pkg/job/watch_dm_notify_price_alert.go
pkg/service/service.go

chore: fix bug service init

---

.github/workflows/ci-test.yml
Makefile
pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi/testdata/get_coin/200-success-eth.json
pkg/handler/defi/testdata/search_coin/200-ok-multiple.json
pkg/handler/defi/testdata/search_coin/200-ok-single.json
pkg/handler/defi/testdata/user_watchlist/post-200-ok-suggest.json
pkg/service/skymavis/mocks/service.go

fix: fix unit test

---

pkg/entities/wallet.go
pkg/handler/wallet/wallet.go
pkg/response/wallet.go
pkg/service/skymavis/mocks/service.go
pkg/service/skymavis/service.go
pkg/service/skymavis/skymavis.go

-   [x] Update wallet NFT response structure

fix: wallet NFT response

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/airdrop_campaign.go
pkg/handler/airdrop-campaign/airdrop_campaign.go
pkg/repo/airdrop_campaign/pg.go
pkg/repo/airdrop_campaign/query.go
pkg/request/airdrop_campaign.go

-   [x] Search airdrop campaign by keyword
-   [x] Search airdrop by id with prefix  **#**
-   ```http://localhost:8200/api/v1/earns/airdrop-campaigns?keyword=airdrop```
-   ```http://localhost:8200/api/v1/earns/airdrop-campaigns?keyword=%23{id}```

feat: search airdrop campaign

---

pkg/entities/wallet.go
pkg/service/krystal/krystal.go

-   [x] Nil when query tracking wallet
-   [x] Both result and error return nil in case `krystal` does not return status code OK

fix: missing handling nil value

---

pkg/entities/wallet.go
pkg/response/wallet.go
pkg/service/skymavis/adapter.go
pkg/service/skymavis/service.go
pkg/service/skymavis/skymavis.go

-   [x] Fetch and parse ronin internal txns from sky mavis (instead of covalent)
`Reason`: Covalent does not respond support internal txns -> cannot recognize RewardClaimed txn

fix: ronin txns parser

---

pkg/entities/wallet.go

-   [x] wallet assets API: ronin - should return empty array instead of null

fix: ronin null balance

---

pkg/repo/airdrop_campaign/pg.go

-   [x] Re-order airdrop campaign, lastest first

chore: reorder airdrop campaign

---

go.mod
go.sum

chore: bump typeset

---

pkg/util/chain.go

feat: add dos chain

---

pkg/entities/defi.go

fix: ticker ape

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/wallet.go
pkg/handler/watchlist.go/interface.go
pkg/handler/watchlist.go/watchlist.go
pkg/repo/user_wallet_watchlist_item/pg.go
pkg/repo/user_wallet_watchlist_item/query.go
pkg/request/wallet.go
pkg/routes/v1.go

-   [x] Rename API `ListTrackingWallets` -> `ListUserTrackingWallets`
-   [x] Add option `withBalance` to ignore calculating wallet balance if not needed
-   [x] Add API `ListTrackingWallets` without user-relation to use for wallet tracking

feat: api get list tracking wallets

---

migrations/schemas/20230711164228-update_user_activity_logs.sql
pkg/entities/guild_user.go
pkg/entities/user.go
pkg/entities/webhook.go
pkg/handler/user/user.go
pkg/handler/webhook/interface.go
pkg/handler/webhook/webhook.go
pkg/model/guild_user_activity_log.go
pkg/model/guild_user_xp.go
pkg/repo/guild_user_activity_log/pg.go
pkg/repo/guild_user_activity_log/store.go
pkg/repo/guild_user_xp/pg.go
pkg/repo/guild_user_xp/query.go
pkg/repo/guild_user_xp/store.go
pkg/request/user.go
pkg/request/webhook.go

-   [x] Store user activities with profile ID

refactor: user activity logs

---

pkg/model/coingecko_supported_tokens.go

-   [x] Coingecko fetcher: fix upsert query error - `detail_platforms` should be `[]` instead of empty string ``

fix: coingecko fetcher job

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user_token_support_request.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/request/token.go
pkg/response/token.go
pkg/routes/v1.go

Add API get custom token by address to serve for show custom token transfer on the wallet tracking message.

feat: add api get custom token by address

---

pkg/entities/configs.go
pkg/job/update_user_roles.go

chore: check member of guild

---

migrations/schemas/20230713-154428-alter_coingecko_detail_platforms.sql
pkg/handler/defi/testdata/search_coin/200-ok-multiple.json
pkg/handler/defi/testdata/search_coin/200-ok-single.json
pkg/model/coingecko_supported_tokens.go
pkg/repo/coingecko_supported_tokens/pg.go

fix: coingecko fetcher - upsert

---

pkg/entities/configs.go
pkg/model/user_nft_balance.go
pkg/repo/user_nft_balance/pg.go

fix: update nft role job

---

cmd/server/main.go
go.mod
go.sum

-   [x] update mochi toolkit lib

chore: update mochi toolkit lib

---

cmd/update-user-nft-balances/main.go
cmd/update-user-role/main.go
pkg/handler/config-roles/config.go
pkg/job/update_user_nft_balance.go
pkg/job/update_user_roles.go
pkg/model/guild_config_group_nft_role.go

-   [x] add option for update user role

feat: add option update user role

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/invest.go
pkg/handler/handler.go
pkg/handler/invest/interface.go
pkg/handler/invest/invest.go
pkg/request/invest.go
pkg/response/invest.go
pkg/routes/v1.go
pkg/service/krystal/krystal.go
pkg/service/krystal/response.go
pkg/service/krystal/service.go

-   [x] add get invest list api
```sh
'http://localhost:8200/api/v1/invests?chainIds=1&platforms=aave_v2&types=lend&status=active' \
```

feat: invest api

---

pkg/repo/vault/pg.go

-   [x] get dicord guild fo vault

chore: get discord guild for vault

---

pkg/entities/configs.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/model.go
pkg/service/mochiprofile/service.go

-   [x]  update api get evm account

chore: update api get evm account

---

pkg/handler/config-roles/config.go
pkg/job/update_user_roles.go

-   [x] fix role config nft set

fix: role config nft set

---

docker-compose.yml
docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20230719085311-add-token-info-table.sql
pkg/config/config.go
pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/model/token_info.go
pkg/repo/repo.go
pkg/repo/token_info/pg.go
pkg/repo/token_info/store.go
pkg/response/defi.go
pkg/routes/v1.go
pkg/service/coingecko/coingecko.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/model.go
pkg/service/geckoterminal/service.go
pkg/service/service.go

feat: add geckoterminal info

---

pkg/entities/offchain_tip_bot.go

-   [x] `/tip/transfer`: sender and recipients input should be profile ID (was discord ID before(

fix: transfer with profile

---

cmd/test/main.go
pkg/entities/defi.go
pkg/response/defi.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/model.go
pkg/service/geckoterminal/service.go
pkg/util/util.go

chore: update token info api

---

migrations/schemas/20230724164203-update-token-infos-table.sql
pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/model/token_info.go
pkg/repo/token_info/pg.go
pkg/repo/token_info/store.go
pkg/response/defi.go
pkg/routes/v1.go
pkg/service/coingecko/coingecko.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/model.go
pkg/service/geckoterminal/service.go

chore: update token info

---

pkg/entities/defi.go

chore: cleanup some token info data

---

pkg/entities/defi.go
pkg/service/geckoterminal/geckoterminal.go

chore: update token info data

---

pkg/entities/defi.go
pkg/response/defi.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/model.go
pkg/service/geckoterminal/service.go

chore: add geckoterminal chart

---

docker-compose.yml
pkg/entities/defi.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/model.go
pkg/service/geckoterminal/service.go

chore: token info use geckoterminal chart api

---

pkg/service/geckoterminal/geckoterminal.go

chore: token info change chain name

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/invest.go
pkg/handler/invest/interface.go
pkg/handler/invest/invest.go
pkg/request/invest.go
pkg/response/invest.go
pkg/routes/v1.go
pkg/service/krystal/krystal.go
pkg/service/krystal/request.go
pkg/service/krystal/response.go
pkg/service/krystal/service.go

-   [x] Onchain invest data
```sh
'http://localhost:8200/api/v1/onchain/invest-stake-data?chainID=1&platform=aave_v2&type=lend&tokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&userAddress=0x5417A03667AbB6A059b3F174c1F67b1E83753046&tokenAmount=1000000000000000000' \
```
```sh
'http://localhost:8200/api/v1/onchain/invest-unstake-data?chainID=1&platform=aave_v2&type=lend&tokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&userAddress=0x5417A03667AbB6A059b3F174c1F67b1E83753046&tokenAmount=1000000000000000000' \
```

feat: onchain invest data

---

pkg/response/defi.go
pkg/service/coingecko/coingecko.go

-   [x] fix api get coin market cap from coin gecko

fix: update CoinGecko.GetCoinsMarketData service

---

pkg/response/defi.go
pkg/service/coingecko/coingecko.go

This reverts commit c81854d6a2946823ee0dd72b4abf0274af11b482.

Revert "fix: update .svc.CoinGecko.GetCoinsMarketData()"

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot.go
pkg/handler/tip/tip.go
pkg/response/offchain_tip_bot.go

-   [x] Update API response `/transfer-v2`

fix: transfer-v2 response

---

pkg/entities/defi.go
pkg/handler/defi/defi.go

-   [x] Return 404 not found if cgk service query coin return not found

fix: convert status response

---

pkg/response/defi.go
pkg/service/coingecko/coingecko.go

-   [x] update get coin market from coingecko

fix: update get coin market from coingecko

---

pkg/model/errors/error.go
pkg/model/errors/validator.go
pkg/service/coingecko/coingecko.go

-   [x] return bad request status

chore: update return api

---

pkg/entities/nfts.go
pkg/handler/nft/nft.go

-   [x] check nft collection api

fix: check nft collection api

---

.chglog/CHANGELOG.tpl.md
.chglog/config.yml
.github/workflows/gke-prod.yml
.github/workflows/post-release.yaml

-   [x] add post release to create a github release after building an image

ci: add release & its notification

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go
pkg/service/mochipay/request.go

fix: transfer v2

---

pkg/entities/offchain_tip_bot.go

-   [x] transfer-v2: fix amount conversion

fix: transfer-v2 amount

---

pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/service/coingecko/coingecko.go

chore: check api defi

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/swap/swap.go
pkg/request/swap.go

-   [x] fix: [[sentry-296]](https://sentry.daf.ug/organizations/dwarves-foundation/issues/296) swap route missing param

fix: [sentry-296] swap route missing param

---

pkg/handler/config-roles/config.go

chore: check config role

---

pkg/handler/airdrop-campaign/airdrop_campaign.go
pkg/handler/dex/dex.go
pkg/handler/tip/tip.go
pkg/handler/user/user.go
pkg/handler/wallet/wallet.go
pkg/handler/watchlist.go/watchlist.go
pkg/util/util.go

-   [x] validate profile id for api

chore: validate profile id

---

pkg/handler/watchlist.go/watchlist.go

-   [x] remove validate profile id

feat: remove validate profile id

---

pkg/handler/wallet/wallet.go

-   [x] remove validate profile id

fix: remove validate profile id

---

go.mod
go.sum
pkg/entities/user.go

-   [x] fix bug that top cmd does not display some unknown users if they don't have username
-  Run the command "/top" to verify if the response is correct.

fix: top cmd does not display some unknown users

---

pkg/entities/emojis.go

fix: get emoji url

---

go.mod
go.sum
migrations/schemas/20230823135230-add-product-changelogs.sql
pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/product_bot_commands.go
pkg/repo/pg/repo.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/query.go
pkg/repo/product_changelogs/store.go
pkg/repo/repo.go
pkg/request/product_data.go
pkg/response/product_metadata.go
pkg/routes/v1.go

-   [x] add product metadata changelog

feat: add product metadata changelog

---

.github/pull_request_template.md

fix: update content template pr

---

migrations/schemas/20230824153220-update_product_changelogs_table.sql
pkg/config/config.go
pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/product_bot_commands.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/store.go
pkg/response/github.go
pkg/routes/v1.go
pkg/service/github/adapter.go
pkg/service/github/github.go
pkg/service/github/service.go
pkg/service/service.go
pkg/util/util.go

-   [x] Crawl changelog from github
-   [x]No UI commands affect by this change
```sh
curl --request POST \
--url http://localhost:8200/api/v1/product-metadata/crawl-changelogs \
--header 'Content-Type: application/json' \
}'
```

feat: get changelog from github

---

pkg/service/mochiprofile/mochiprofile.go

- Update request method for mark user onboarding status

chore: update request method mark user onboarding

---

pkg/entities/offchain_tip_bot.go

fix: store message transfer token

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go

fix: send more params tip moniker

---

pkg/entities/offchain_tip_bot.go

fix: allow tip equal bal

---

pkg/entities/wallet.go
pkg/service/covalent/covalent.go

feat: asset base chain

---

pkg/entities/wallet.go

fix: rm retry query coingecko sol token

---

.github/workflows/ci-test.yml
go.mod
pkg/handler/config-roles/config.go

- fix: add logging for start and completion of updateUserRoles
- fix: run updateUserRoles in a goroutine to avoid blocking the request
- ci: update CI test, use pg, redis as GA services instead of using docker compose
- ci: add Go cache 
- /role token set
- /role token remove
- /role nft set

fix: run updateUserRoles in a goroutine to avoid blocking the request

---

pkg/entities/tokens.go

Support calculating token balance in chain BASE

chore: support calculating token balance in chain BASE

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go

feat: tip with original tx id

---

pkg/service/mochiprofile/mochiprofile.go

chore: update convention query param

---

migrations/schemas/20230907160130-create_profile_command_usages_table.sql

feat: add command table

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go

fix: store original tip amount

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go

fix(tip): include channel id to notification payload

---

pkg/entities/onboarding.go
pkg/service/mochiprofile/model.go

fix: update response get onboarding status

---

go.mod
go.sum
migrations/schemas/20230911105520-create_product_changelog_snapshot.sql
pkg/entities/product_data.go
pkg/kafka/message/new_changelog.go
pkg/model/product_bot_commands.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/store.go

feat: check new changelog

---

pkg/entities/defi.go
pkg/handler/defi/defi.go
pkg/handler/defi/interface.go
pkg/request/defi.go
pkg/response/friend_tech.go
pkg/routes/v1.go
pkg/service/coingecko/mocks/service.go
pkg/service/friendtech/friend_tech.go
pkg/service/friendtech/service.go
pkg/service/service.go

simple search for friend scan keys

feat: simple search for friend scan keys

---

migrations/schemas/20230913134106-create_table_product_hashtags.sql
pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/product_hashtag.go
pkg/model/product_hashtag_alias.go
pkg/repo/pg/repo.go
pkg/repo/product_hashtag/pg.go
pkg/repo/product_hashtag/store.go
pkg/repo/repo.go
pkg/request/product_data.go
pkg/routes/v1.go

feat: data hashtag and api render

---

cmd/watch-key-price-change/main.go
docker-compose.yml
go.mod
go.sum
pkg/entities/defi.go
pkg/entities/friend_tech_key.go
pkg/handler/defi/defi.go
pkg/job/watch_key_price_change.go
pkg/kafka/message/price_change_alert.go
pkg/model/friend_tech_key.go
pkg/repo/friend_tech_key_watchlist_item/pg.go
pkg/repo/friend_tech_key_watchlist_item/store.go
pkg/response/friend_tech.go
pkg/service/friendtech/friend_tech.go
pkg/service/friendtech/service.go

- Detect the account should receive the alert message after the price changed
- Push the alert data to Kafka

feat: push key price change alert to

---

pkg/entities/offchain_tip_bot.go

fix: store hashtag template in metadata

---

pkg/job/watch_key_price_change.go
pkg/kafka/message/price_change_alert.go
pkg/model/friend_tech_key.go

add more metadata in key price change payload to kafka message

chore: add metadata in key price change to kafka message

---

migrations/schemas/20230914101656-alter_table_hashtag_add_telegram_title.sql
pkg/model/product_hashtag.go

chore: add telegram title hashtag

---

migrations/schemas/20230914113553-alter_table_hashtag_add_telegram_description.sql
pkg/model/product_hashtag.go

chore: add email title hashtag

---

.env.sample
cmd/track-friend-tech-keys/main.go
docs/swagger.yaml
go.mod
go.sum
migrations/schemas/20230914022044-add-notnull-default-for-table-friend-tech-wl.sql
pkg/entities/friend_tech_key.go
pkg/job/track_friend_tech_keys.go
pkg/model/friend_tech_key.go
pkg/repo/friend_tech_key_watchlist_item/pg.go
pkg/repo/friend_tech_key_watchlist_item/store.go
pkg/response/friend_tech.go
pkg/service/friendtech/friend_tech.go
pkg/service/friendtech/service.go
pkg/util/util.go

- Migrate table `friend_tech_key_watchlist_items` to add some constraints
- Add job to track friend tech keys new txs come and push message for notification

feat: job to track friend tech keys new txs come

---

pkg/entities/emojis.go
pkg/handler/emojis/emojis.go
pkg/repo/emojis/pg.go
pkg/repo/emojis/query.go
pkg/repo/emojis/store.go
pkg/request/product_data.go
pkg/service/discord/discord.go

feat: paginate emojis

---

pkg/repo/emojis/pg.go

fix: count total emojis in pagination

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go

fix(tip): add channel name for tip notification

---

pkg/entities/offchain_tip_bot.go

fix: handle not found hashtag etmplate

---

pkg/entities/offchain_tip_bot.go
pkg/repo/product_hashtag/pg.go

fix: support insensitive hashtag template

---

pkg/entities/user_token_support_request.go
pkg/service/coingecko/adapter.go

- Find token by contract (coingecko): cache even if contract not found

fix: cache - find by contract

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/response/friend_tech.go

Medata currently is response in camelCase, must change to snake_case for compatible

fix: use snake_case in friend metadata response

---

pkg/entities/offchain_tip_bot.go
pkg/request/mochi_pay_transfer.go
pkg/request/offchain_tip_bot.go

fix(tip): add channel url to transferv2 payload

---

pkg/entities/guild.go
pkg/handler/guild/guild.go
pkg/handler/guild/interface.go
pkg/repo/guild_users/pg.go
pkg/repo/guild_users/store.go
pkg/request/guild.go
pkg/routes/v1.go

feat: validate profile is member of server

---

cmd/cache-profile-commands/main.go
migrations/schemas/20230915164412-alter_command_usage_add_user_platform_id.sql
pkg/entities/entity.go
pkg/job/cache_profile_commands.go
pkg/model/profile_command_usage.go
pkg/repo/pg/repo.go
pkg/repo/profile_command_usage/pg.go
pkg/repo/profile_command_usage/store.go
pkg/repo/repo.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/service.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/service.go
pkg/util/util.go

- New job: cache top 5 profiles with most `/profile` usage
- /profile

feat: job - cache top profile cmd usage

---

pkg/entities/emojis.go
pkg/handler/emojis/emojis.go
pkg/request/product_data.go

feat: support emoji query native token

---

pkg/response/friend_tech.go

Need camelCase to handle friend tech API response, and snake case to return to Mochi client

fix: convert friend tech key from camelCase to snake_case

---

pkg/entities/defi.go

fix(compare-token): handle case token not found return 404

---

pkg/entities/defi.go
pkg/service/chainexplorer/chainexplorer.go
pkg/service/service.go

refactor(gas-tracker): improve api latency by caching

---

pkg/service/discord/discord.go

- Hotfix guild id list to validate emojis

fix: guild id list to validate emoji

---

cmd/server/main.go

fix: allow request id header cors

---

cmd/server/main.go

fix: allow all origin cors

---

pkg/service/discord/discord.go

- Handle error when getting emoji guilds

fix: handle error when get emojis

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
migrations/schemas/20231010071714-add-tono-command-permissions-table.sql
pkg/entities/tono.go
pkg/handler/handler.go
pkg/handler/tono/interface.go
pkg/handler/tono/tono.go
pkg/model/tono_command_permission.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/tono_command_permission/pg.go
pkg/repo/tono_command_permission/query.go
pkg/repo/tono_command_permission/store.go
pkg/request/tono_command_permission.go
pkg/response/tono.go
pkg/routes/v1.go

feat: tono command permission manage

---

pkg/util/chain.go
pkg/util/marketplace.go

- Add changes to support integrate new chain `zkSync`
- None
-

feat: integrate chain zkSync

---

migrations/schemas/20231031133013-create_table_theme.sql
pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/product_theme.go
pkg/repo/pg/repo.go
pkg/repo/product_theme/pg.go
pkg/repo/product_theme/store.go
pkg/repo/repo.go
pkg/request/product_data.go
pkg/routes/v1.go

feat: product themes

---

go.mod
go.sum
pkg/entities/defi.go

fix: query ticker rune

---

pkg/handler/watchlist.go/watchlist.go

fix: cannot bind uri remove wl

---

pkg/handler/tip/tip.go
pkg/middleware/auth.go
pkg/routes/v1.go

- `/transfer-v2`: authorize requester

fix: transfer-v2 auth

---

pkg/handler/tip/tip.go
pkg/middleware/auth.go

- Update authorization logic for transfer-v2

fix: transfer-v2 authorization

---

pkg/util/chain.go
pkg/util/marketplace.go

- Add changes to support integrate new chain `Mantle`
- None
-

feat: integrate chain Mantle

---

pkg/config/config.go
pkg/entities/command_permission.go

fix: rename env name application id

---

pkg/entities/tokens.go

fix: support mnt for update user role

---

pkg/entities/dao_proposal.go
pkg/entities/tokens.go
pkg/job/update_user_token_roles.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/service.go

fix: apply get list profile for token role update

---

pkg/entities/offchain_tip_bot.go
pkg/entities/vault.go
pkg/request/offchain_tip_bot.go
pkg/request/vault.go

fix: track channel tip tx

---

cmd/server/main.go
cmd/update-user-token-roles/main.go
go.mod
go.sum
pkg/config/config.go
pkg/handler/config-roles/config.go
pkg/job/update_user_token_roles.go
pkg/service/sentrygo/sentrygo.go
pkg/service/sentrygo/service.go
pkg/service/service.go

chore: capture sentry message user token role

---

pkg/job/update_user_token_roles.go

fix: update token role log

---

pkg/job/update_user_token_roles.go
pkg/service/mochiprofile/mochiprofile.go

fix: update token role get profile by 50 batch

---

pkg/config/config.go

fix: mochi secret env

---

migrations/schemas/20231117133803-alter_tokens_add_chain_id.sql
pkg/entities/configs.go
pkg/model/offchain_tip_bot_token.go

fix: enrich token price moniker

---

pkg/config/config.go
pkg/entities/swap_util.go
pkg/entities/wallet.go
pkg/entities/wallet_utils.go
pkg/response/wallet.go
pkg/service/birdeye/birdeye.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/service.go

fix: return id wallet onchain

---

pkg/entities/wallet_utils.go

fix: wrong compare address onchain asset

---

go.mod
go.sum

fix: bump toolkit typeset version

---

pkg/entities/user_token_support_request.go

fix: get custom token null

---

pkg/entities/defi.go

fix: query geckoterminal not found return empty

---

pkg/entities/vault.go

fix: logic vault

---

cmd/update-user-role/main.go
pkg/job/update_user_roles.go
pkg/job/update_user_token_roles.go
pkg/service/sentrygo/sentrygo.go
pkg/service/sentrygo/service.go

chore: update title sentry cronjob

---

cmd/check-validate-emoji/main.go
cmd/fetch-coingecko-tokens/main.go
pkg/job/check_invalidate_emoji.go
pkg/job/fetch_coingecko_tokens.go
pkg/job/update_user_roles.go
pkg/job/update_user_token_roles.go
pkg/util/discord.go

fix: add sentry for cj invalidate emoji and fetch coingecko token

---

pkg/entities/offchain_tip_bot.go
pkg/repo/product_theme/pg.go
pkg/repo/product_theme/store.go
pkg/request/offchain_tip_bot.go

fix: add theme transaction

---

pkg/entities/defi.go

fix: handle coingecko id not found

---

pkg/entities/defi.go

fix: ignore search coingecko if query empty

---

pkg/service/chainexplorer/chainexplorer.go

fix: handle retry getting gas tracker

---

pkg/entities/guild.go
pkg/handler/guild/guild.go
pkg/handler/guild/interface.go
pkg/routes/v1.go

fix: restore api create guild

---

pkg/entities/user.go

fix: slow response gm webhook

---

pkg/util/util.go

fix: handle timeout 3rd party

---

pkg/service/birdeye/birdeye.go
pkg/service/skymavis/adapter.go

fix: handle rate limit skymavis

---

migrations/schemas/20231201140808-add_address_native_token.sql
pkg/model/offchain_tip_bot_token.go

fix: add fields moniker default

---

migrations/schemas/20231201141525-add_decimal_moniker_default.sql
pkg/model/offchain_tip_bot_token.go

fix: add decimal moniker

---

pkg/service/birdeye/birdeye.go

- Birdeye: update request error message

fix: birdeye requests - update error msg

---

pkg/entities/wallet.go

fix: handle non supported wallet

---

pkg/util/util.go

fix: resolve crash

---

migrations/schemas/20231205193453-add_chain_type.sql
pkg/entities/configs.go
pkg/model/chain.go
pkg/model/offchain_tip_bot_token.go

fix: add chain type

---

pkg/cache/redis.go
pkg/config/config.go
pkg/entities/entity.go
pkg/handler/webhook/webhook_test.go
pkg/job/watch_coin_price_change.go
pkg/job/watch_dm_notify_price_alert.go
pkg/job/watch_key_price_change.go
pkg/service/service.go

- backward compatible to single redis cfg

feat: add redis sentiel url env

---

pkg/util/util.go

fix: extend timeout url

---

pkg/entities/vault.go
pkg/entities/wallet.go

fix(vault): update correct key to query evm assets

---

pkg/service/nghenhan/nghenhan.go

- Init sentry for nghenhan svc

fix: nghenhan - init sentry

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/offchain_tip_bot.go
pkg/handler/config/config.go
pkg/handler/tip/tip.go
pkg/request/offchain_tip_bot.go
pkg/service/apilayer/apilayer.go
pkg/service/birdeye/birdeye.go
pkg/service/chainexplorer/chainexplorer.go
pkg/service/friendtech/friend_tech.go
pkg/service/github/adapter.go
pkg/service/krystal/krystal.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/response.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/nghenhan/nghenhan.go
pkg/service/skymavis/adapter.go
pkg/util/util.go

- transfer v2: update validation

fix: transfer-v2 validation

---

pkg/service/coingecko/adapter.go
pkg/service/coingecko/coingecko.go
pkg/util/util.go

fix: cache market data coingecko

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user.go
pkg/handler/user/interface.go
pkg/handler/user/user.go
pkg/request/user.go
pkg/response/user.go
pkg/routes/v1.go

- Mock API: get profile's global info

feat: mock API - global profile info

---

pkg/service/nghenhan/nghenhan.go

fix: add retry nghenhan service

---

pkg/entities/vault.go
pkg/service/covalent/adapter.go

fix: temp solution handle exceed covalent quote

---

pkg/entities/vault.go
pkg/entities/wallet.go
pkg/request/wallet.go

fix: remove base when get balance vault

---

cmd/server/main.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/setting.go
pkg/handler/handler.go
pkg/handler/setting/general.go
pkg/handler/setting/interface.go
pkg/handler/setting/notification.go
pkg/handler/setting/setting.go
pkg/model/notification_flag.go
pkg/model/payment_setting.go
pkg/model/privacy_setting.go
pkg/model/user_notification_setting.go
pkg/request/setting.go
pkg/response/setting.go
pkg/routes/v1.go

- Define model for Mochi settings
- Payment settings
- Privacy settings
- Notification settings
- [Mock] CRUD API for Mochi Settings

feat: mochi settings

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/setting.go
pkg/handler/setting/interface.go
pkg/handler/setting/notification.go
pkg/request/setting.go
pkg/routes/v1.go

- Update noti settings API: small tweak - allow to update all noti settings in one endpoint

fix: small tweak - update noti settings API

---

migrations/schemas/20231220175921-seed_notification_flags.sql
pkg/entities/setting.go

- Notification flags: update migration and init data

fix: init notification flags

---

pkg/entities/setting.go

- User notification flags: init default as true

fix: init user notification flags

---

migrations/schemas/20231222113146-remove_payment_setting_default_token.sql
pkg/entities/setting.go
pkg/model/user_payment_setting.go
pkg/request/setting.go

- Payment settings: remove default tokens

fix: payment settings - remove default token

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/setting.go
pkg/request/setting.go

- Update noti settings: 400 error when update with `enable` = false
- Update swagger

fix: update noti settings

---

pkg/entities/wallet.go
pkg/entities/wallet_utils.go
pkg/response/defi.go
pkg/service/geckoterminal/geckoterminal.go
pkg/service/geckoterminal/service.go
pkg/service/service.go

fix: render sol wallet

---

pkg/entities/emojis.go
pkg/entities/wallet_utils.go
pkg/repo/emojis/pg.go
pkg/repo/emojis/store.go
pkg/response/wallet.go

fix: add icon wallet asset

---

pkg/entities/defi.go
pkg/request/defi.go
pkg/response/defi.go

fix: user watchlist token remove pagination

---

pkg/entities/wallet.go
pkg/service/binance/adapter/adapter.go
pkg/service/binance/utils/request.go

fix: update binance query api

---

pkg/entities/wallet.go

fix: remove cache total amt binance

---

pkg/entities/setting.go
pkg/handler/setting/general.go
pkg/handler/setting/notification.go
pkg/request/setting.go
pkg/util/slice/slice.go
pkg/util/uuid/uuid.go

fix: notification settings - add validation

---

pkg/entities/emojis.go
pkg/handler/emojis/emojis.go

remove pagination if query emojis with codes
n/a

fix(emojis): remove pagination when query emojis list with codes

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/vault.go
pkg/handler/vault/vault.go
pkg/repo/vault/pg.go
pkg/repo/vault/query.go
pkg/request/vault.go

- Get vaults API: allow to filter by list of vault ID

fix: update get vaults API

---

pkg/entities/wallet_utils.go
pkg/service/binance/adapter/adapter.go
pkg/service/binance/binance.go

fix: remove unused cache binance

---

pkg/entities/defi.go
pkg/entities/defi_test.go
pkg/entities/tokens.go
pkg/handler/defi/defi.go

fix: multiple ticker

---

pkg/entities/product_data.go

fix: temp disable changelog notify

---

pkg/entities/setting.go
pkg/request/setting.go

- User privacy settings: update initial configuration
- Update privacy setting validation
- Update tx limit setting validation

fix: user privacy settings - update initial configuration

---

pkg/entities/setting.go
pkg/handler/setting/general.go
pkg/request/setting.go

fix: validate money source

---

pkg/entities/offchain_tip_bot.go

fix: transfer-v2 - overwrited metadata

---

migrations/schemas/20240110161335-update_user_privacy_settings.sql
pkg/entities/setting.go
pkg/model/user_privacy_setting.go
pkg/request/setting.go

fix: privacy settings - update structure

---

pkg/entities/user.go
pkg/response/user.go

Add more data for user balances api
n/a

fix(userBalance): add more data for user balances api

---

pkg/entities/user.go
pkg/entities/wallet_utils.go
pkg/service/mochipay/response.go

Update API get balances
/balances

fix: add more data for user balances api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/user/user.go

fix: add swagger for get user total balances

---

pkg/entities/wallet.go
pkg/entities/wallet_utils.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/response.go
pkg/service/mochipay/service.go

feat: wallet sol render lending

---

pkg/entities/wallet.go

fix: not filter native token in asset

---

pkg/entities/offchain_tip_bot.go

handle nil token when not supported
n/a
- [ x] Include the sample call / example in this PR

fix: handle nil token when not supported

---

pkg/entities/setting.go
pkg/model/user_payment_setting.go
pkg/request/setting.go

- Update list of available default receiver platforms
- Allow to enable/disable default message settings

fix: update payment setting API

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml

fix: update setting swagger

---

pkg/entities/wallet.go

change response of api get assets
n/a

fix: change response chain name of api get assets

---

migrations/schemas/20240116151230-alter_product_changelogs_add_version.sql
pkg/model/product_bot_commands.go

fix(product-changelog): add version field

---

pkg/entities/product_data.go

fix(product-changelog): get changelog version

---

pkg/entities/setting.go

fix: payment settings - use balances as prioritized tokens

---

pkg/entities/setting.go

fix: payment settings - init prioritized tokens got null

---

pkg/repo/product_changelogs_view/pg.go

fix(changelog): update unique value for product changelog view

---

pkg/entities/setting.go
pkg/handler/setting/notification.go
pkg/request/setting.go

- Update noti settings: fix noti flags input validation

fix: update noti settings validation

---

pkg/entities/user.go
pkg/entities/wallet.go
pkg/entities/wallet_utils.go
pkg/handler/dex/dex.go
pkg/response/wallet.go
pkg/util/util.go

fix: mock pnl changes of tokens in balances api

---

pkg/entities/product_data.go
pkg/handler/product-data/product_data.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/query.go
pkg/repo/product_changelogs/store.go
pkg/request/product_data.go
pkg/response/product_metadata.go

fix: add pagination changelog

---

pkg/entities/product_data.go
pkg/kafka/message/new_changelog.go

fix(changelog): push new changelog notification data

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml

fix: gen swagger for pnl token changes

---

pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/product_bot_commands.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/store.go
pkg/routes/v1.go

```sh
curl --request GET \
--url http://localhost:8200/api/v1/product-metadata/changelogs/1.51.0 
```

feat: get changelog detail by version

---

pkg/entities/wallet.go

fix: filter old base contract

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/product-data/product_data.go

fix: gen swagger for changelog

---

go.mod
go.sum
migrations/schemas/20242301162030-alter_product_changelog_snapshot_add_is_publish.sql
pkg/config/config.go
pkg/entities/product_data.go
pkg/handler/product-data/interface.go
pkg/handler/product-data/product_data.go
pkg/model/markdown.go
pkg/model/product_bot_commands.go
pkg/repo/product_changelogs/pg.go
pkg/repo/product_changelogs/query.go
pkg/repo/product_changelogs/store.go
pkg/request/product_data.go
pkg/routes/v1.go

fix(changelog): add public changelog flow

---

pkg/model/product_bot_commands.go

fix(changelog): update changelog model

---

pkg/entities/product_data.go

fix(changelog): handle parse markdown

---

pkg/entities/product_data.go

fix(changelog): update changelog preview ui

---

pkg/entities/product_data.go

fix: typo changelog parsing

---

pkg/service/geckoterminal/geckoterminal.go

Try to passing Cloudflare secure check. If it is not work, can consider to use proxy later. 
```
{"hostname":"mochi-api-ff8f44b-wlvmd","level":"info","msg":"invalid raw data from geckoterminal: app.geckoterminal.com\nChecking if the site connection is secure\napp.geckoterminal.com needs to review the security of your connection before proceeding.\nRay ID: 84af36cb585ca3e0\nPerformance \u0026 security by Cloudflare","service":"mochi-api","time":"2024-01-25T08:40:56Z"}
```

fix: try passing cloudflare when searching geckoterminal

---

pkg/consts/changelog.go
pkg/entities/product_data.go

fix(changelog): update parse markdown

---

migrations/schemas/20240126153419-add-table-token-price-snapshot.sql
pkg/entities/user.go
pkg/entities/wallet_utils.go
pkg/model/token_price_snapshot.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/repo/token_price_snapshot/pg.go
pkg/repo/token_price_snapshot/store.go
pkg/service/binance/adapter/adapter.go

fix: add snapshot price to calcualte pnl token change

---

pkg/entities/user.go

fix: resposne token pnl in api balances

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/handler/product-data/product_data.go
pkg/response/product_metadata.go

fix(changelog): update response api

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/setting.go
pkg/handler/setting/interface.go
pkg/handler/setting/tip_message.go
pkg/response/setting.go
pkg/routes/v1.go

feat: get default tip message

---

pkg/entities/product_data.go

fix(changelog): parse markdown content

---

pkg/entities/wallet.go

handle err when not found binance future data
e.g: /balances

feat: handle err when not found binance future data

---

pkg/entities/wallet.go

binding future binance to asset
e.g: /balances

fix: binding future binance to asset

---

pkg/entities/user.go
pkg/entities/wallet.go
pkg/response/wallet.go

fix: seperate data binance

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/entities/user.go
pkg/entities/wallet.go
pkg/response/wallet.go

add pnl token in future asset
e.g: /balances

fix: add pnl token for future binance asset

---

pkg/entities/verification.go

fix(verify): send verify component

---

pkg/entities/verification.go
pkg/service/discord/discord.go
pkg/util/token.go

fix(feedback): handle user feedback

---

pkg/util/util.go

Error: `invalid character '<' looking for beginning of value`
Non JSON error is return (usually 503 because of spamming or rate limit of ext service) let us can't unmarshal response. The error unmarshalling is raise instead of right error. 
So firstly, I handle 503. Then also handle the error return in the HTML format without right status code.
Example:

fix: handle non json response and 503 when sending ext reqeust

---

pkg/repo/product_changelogs/pg.go

fix(changelog): update get changelog api

---

pkg/entities/guild.go
pkg/handler/guild/guild.go
pkg/handler/guild/interface.go
pkg/response/guild.go
pkg/routes/v1.go

feat: report guild member

---

pkg/entities/guild.go
pkg/handler/guild/guild.go
pkg/request/guild.go
pkg/response/guild.go

feat: report guild additional roles

---

pkg/entities/offchain_tip_bot.go
pkg/request/offchain_tip_bot.go
pkg/service/mochipay/mochipay.go
pkg/service/mochipay/service.go
pkg/util/slice/slice.go

- Transfer v2: update payload - add `token_id`. If token_id is specified, use this to get the respective token. Otherwise find token by chain_id + symbol

fix: transfer-v2 - add token_id to payload

---

pkg/response/defi.go

- Fix: get coin - add `ico_data` to response

fix: get coin - update response

---

pkg/entities/product_data.go

fix(changelog): remove filter image

---

pkg/entities/dex.go
pkg/handler/dexes/dex.go
pkg/handler/dexes/interface.go
pkg/request/dex.go
pkg/routes/v1.go
pkg/service/dexscreener/dexscreener.go
pkg/service/dexscreener/dexscreener_test.go
pkg/service/dexscreener/service.go

- New API: Search for Dex Screener pairs

feat: search dex-screener pairs

---

pkg/response/defi.go

- Get Coin: Update coingecko tickers response model

fix: update coingecko tickers response model

---

pkg/entities/defi.go
pkg/response/defi.go

- Get coin: use DexScreener if coingecko data is stale

fix: get coin - use dexscreener if coingecko data is stale

---

pkg/entities/user.go

fix: get user balances

---

pkg/entities/wallet_utils.go

fix: fix summarize wallets bals of wallets

---

pkg/entities/wallet.go

fix: remove old icy

---

README.MD

fix: bump version

---

pkg/service/binance/adapter/adapter.go

fix: remove pp print

---

pkg/entities/wallet.go
pkg/model/binance_asset_average_cost.go
pkg/repo/binance_spot_transaction/pg.go

fix: update dca formula

---

pkg/repo/binance_spot_transaction/pg.go
pkg/repo/binance_spot_transaction/store.go
pkg/scheduler/update-binance-spot-history.go
pkg/service/binance/adapter/adapter.go
pkg/service/binance/binance.go
pkg/service/binance/service.go

fix: update spot tx when it status is new

---

pkg/service/krystal/krystal.go

fix: update cache time krystal balance fetcher

---

pkg/entities/wallet.go
pkg/response/binance.go

fix: resp tx price in usd for binance spot tx

---

cmd/update-user-onchain-asset-average-cost/main.go
migrations/schemas/20240531090511-add-onchain-asset-avg-costs-table.sql
pkg/config/config.go
pkg/entities/onchain_asset_avg_cost.go
pkg/entities/swap.go
pkg/handler/swap/interface.go
pkg/handler/swap/swap.go
pkg/job/update_user_onchain_asset_average_cost.go
pkg/model/onchain_asset_avg_cost.go
pkg/repo/onchain_asset_avg_cost/pg.go
pkg/repo/onchain_asset_avg_cost/store.go
pkg/repo/pg/repo.go
pkg/repo/repo.go
pkg/request/swap.go
pkg/routes/v1.go
pkg/service/dune/adapter/adapter.go
pkg/service/dune/adapter/do.go
pkg/service/dune/adapter/response.go
pkg/service/dune/dune.go
pkg/service/dune/service.go
pkg/service/mochiprofile/mochiprofile.go
pkg/service/mochiprofile/service.go
pkg/service/service.go

feat: get onchain asset average cost

---

pkg/repo/onchain_asset_avg_cost/pg.go

fix: search case insensitive onchain avg cost

---

pkg/job/update_user_onchain_asset_average_cost.go

fix: get average cost assets support solana
